// Code generated by ent, DO NOT EDIT.

package paymentinvoicedocument

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the paymentinvoicedocument type in the database.
	Label = "payment_invoice_document"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInvoiceRequestID holds the string denoting the invoice_request_id field in the database.
	FieldInvoiceRequestID = "invoice_request_id"
	// FieldFilename holds the string denoting the filename field in the database.
	FieldFilename = "filename"
	// FieldContentType holds the string denoting the content_type field in the database.
	FieldContentType = "content_type"
	// FieldSizeBytes holds the string denoting the size_bytes field in the database.
	FieldSizeBytes = "size_bytes"
	// FieldSha256 holds the string denoting the sha256 field in the database.
	FieldSha256 = "sha256"
	// FieldData holds the string denoting the data field in the database.
	FieldData = "data"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeInvoiceRequest holds the string denoting the invoice_request edge name in mutations.
	EdgeInvoiceRequest = "invoice_request"
	// Table holds the table name of the paymentinvoicedocument in the database.
	Table = "payment_invoice_documents"
	// InvoiceRequestTable is the table that holds the invoice_request relation/edge.
	InvoiceRequestTable = "payment_invoice_documents"
	// InvoiceRequestInverseTable is the table name for the PaymentInvoiceRequest entity.
	// It exists in this package in order to avoid circular dependency with the "paymentinvoicerequest" package.
	InvoiceRequestInverseTable = "payment_invoice_requests"
	// InvoiceRequestColumn is the table column denoting the invoice_request relation/edge.
	InvoiceRequestColumn = "invoice_request_id"
)

// Columns holds all SQL columns for paymentinvoicedocument fields.
var Columns = []string{
	FieldID,
	FieldInvoiceRequestID,
	FieldFilename,
	FieldContentType,
	FieldSizeBytes,
	FieldSha256,
	FieldData,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	FilenameValidator func(string) error
	// DefaultContentType holds the default value on creation for the "content_type" field.
	DefaultContentType string
	// ContentTypeValidator is a validator for the "content_type" field. It is called by the builders before save.
	ContentTypeValidator func(string) error
	// Sha256Validator is a validator for the "sha256" field. It is called by the builders before save.
	Sha256Validator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PaymentInvoiceDocument queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInvoiceRequestID orders the results by the invoice_request_id field.
func ByInvoiceRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceRequestID, opts...).ToFunc()
}

// ByFilename orders the results by the filename field.
func ByFilename(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilename, opts...).ToFunc()
}

// ByContentType orders the results by the content_type field.
func ByContentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentType, opts...).ToFunc()
}

// BySizeBytes orders the results by the size_bytes field.
func BySizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSizeBytes, opts...).ToFunc()
}

// BySha256 orders the results by the sha256 field.
func BySha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSha256, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByInvoiceRequestField orders the results by invoice_request field.
func ByInvoiceRequestField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInvoiceRequestStep(), sql.OrderByField(field, opts...))
	}
}
func newInvoiceRequestStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InvoiceRequestInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, InvoiceRequestTable, InvoiceRequestColumn),
	)
}
