// Code generated by ent, DO NOT EDIT.

package paymentinvoicedocument

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldLTE(FieldID, id))
}

// InvoiceRequestID applies equality check predicate on the "invoice_request_id" field. It's identical to InvoiceRequestIDEQ.
func InvoiceRequestID(v int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldInvoiceRequestID, v))
}

// Filename applies equality check predicate on the "filename" field. It's identical to FilenameEQ.
func Filename(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldFilename, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldContentType, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldSizeBytes, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldSha256, v))
}

// Data applies equality check predicate on the "data" field. It's identical to DataEQ.
func Data(v []byte) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldData, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldUpdatedAt, v))
}

// InvoiceRequestIDEQ applies the EQ predicate on the "invoice_request_id" field.
func InvoiceRequestIDEQ(v int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDNEQ applies the NEQ predicate on the "invoice_request_id" field.
func InvoiceRequestIDNEQ(v int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNEQ(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDIn applies the In predicate on the "invoice_request_id" field.
func InvoiceRequestIDIn(vs ...int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldIn(FieldInvoiceRequestID, vs...))
}

// InvoiceRequestIDNotIn applies the NotIn predicate on the "invoice_request_id" field.
func InvoiceRequestIDNotIn(vs ...int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNotIn(FieldInvoiceRequestID, vs...))
}

// FilenameEQ applies the EQ predicate on the "filename" field.
func FilenameEQ(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldFilename, v))
}

// FilenameNEQ applies the NEQ predicate on the "filename" field.
func FilenameNEQ(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNEQ(FieldFilename, v))
}

// FilenameIn applies the In predicate on the "filename" field.
func FilenameIn(vs ...string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldIn(FieldFilename, vs...))
}

// FilenameNotIn applies the NotIn predicate on the "filename" field.
func FilenameNotIn(vs ...string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNotIn(FieldFilename, vs...))
}

// FilenameGT applies the GT predicate on the "filename" field.
func FilenameGT(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldGT(FieldFilename, v))
}

// FilenameGTE applies the GTE predicate on the "filename" field.
func FilenameGTE(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldGTE(FieldFilename, v))
}

// FilenameLT applies the LT predicate on the "filename" field.
func FilenameLT(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldLT(FieldFilename, v))
}

// FilenameLTE applies the LTE predicate on the "filename" field.
func FilenameLTE(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldLTE(FieldFilename, v))
}

// FilenameContains applies the Contains predicate on the "filename" field.
func FilenameContains(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldContains(FieldFilename, v))
}

// FilenameHasPrefix applies the HasPrefix predicate on the "filename" field.
func FilenameHasPrefix(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldHasPrefix(FieldFilename, v))
}

// FilenameHasSuffix applies the HasSuffix predicate on the "filename" field.
func FilenameHasSuffix(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldHasSuffix(FieldFilename, v))
}

// FilenameEqualFold applies the EqualFold predicate on the "filename" field.
func FilenameEqualFold(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEqualFold(FieldFilename, v))
}

// FilenameContainsFold applies the ContainsFold predicate on the "filename" field.
func FilenameContainsFold(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldContainsFold(FieldFilename, v))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldContainsFold(FieldContentType, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldLTE(FieldSizeBytes, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldContainsFold(FieldSha256, v))
}

// DataEQ applies the EQ predicate on the "data" field.
func DataEQ(v []byte) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldData, v))
}

// DataNEQ applies the NEQ predicate on the "data" field.
func DataNEQ(v []byte) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNEQ(FieldData, v))
}

// DataIn applies the In predicate on the "data" field.
func DataIn(vs ...[]byte) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldIn(FieldData, vs...))
}

// DataNotIn applies the NotIn predicate on the "data" field.
func DataNotIn(vs ...[]byte) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNotIn(FieldData, vs...))
}

// DataGT applies the GT predicate on the "data" field.
func DataGT(v []byte) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldGT(FieldData, v))
}

// DataGTE applies the GTE predicate on the "data" field.
func DataGTE(v []byte) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldGTE(FieldData, v))
}

// DataLT applies the LT predicate on the "data" field.
func DataLT(v []byte) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldLT(FieldData, v))
}

// DataLTE applies the LTE predicate on the "data" field.
func DataLTE(v []byte) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldLTE(FieldData, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasInvoiceRequest applies the HasEdge predicate on the "invoice_request" edge.
func HasInvoiceRequest() predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, InvoiceRequestTable, InvoiceRequestColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvoiceRequestWith applies the HasEdge predicate on the "invoice_request" edge with a given conditions (other predicates).
func HasInvoiceRequestWith(preds ...predicate.PaymentInvoiceRequest) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(func(s *sql.Selector) {
		step := newInvoiceRequestStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentInvoiceDocument) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentInvoiceDocument) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentInvoiceDocument) predicate.PaymentInvoiceDocument {
	return predicate.PaymentInvoiceDocument(sql.NotPredicates(p))
}
