// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountpool"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountPoolUpdate is the builder for updating AccountPool entities.
type AccountPoolUpdate struct {
	config
	hooks    []Hook
	mutation *AccountPoolMutation
}

// Where appends a list predicates to the AccountPoolUpdate builder.
func (_u *AccountPoolUpdate) Where(ps ...predicate.AccountPool) *AccountPoolUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountPoolUpdate) SetUpdatedAt(v time.Time) *AccountPoolUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountPoolUpdate) SetName(v string) *AccountPoolUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountPoolUpdate) SetNillableName(v *string) *AccountPoolUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *AccountPoolUpdate) SetPlatform(v string) *AccountPoolUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *AccountPoolUpdate) SetNillablePlatform(v *string) *AccountPoolUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *AccountPoolUpdate) SetNotes(v string) *AccountPoolUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *AccountPoolUpdate) SetNillableNotes(v *string) *AccountPoolUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *AccountPoolUpdate) ClearNotes() *AccountPoolUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// Mutation returns the AccountPoolMutation object of the builder.
func (_u *AccountPoolUpdate) Mutation() *AccountPoolMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountPoolUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountPoolUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountPoolUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountPoolUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountPoolUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountpool.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountPoolUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accountpool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountPool.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := accountpool.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "AccountPool.platform": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountPoolUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountpool.Table, accountpool.Columns, sqlgraph.NewFieldSpec(accountpool.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountpool.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accountpool.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(accountpool.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(accountpool.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(accountpool.FieldNotes, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountpool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountPoolUpdateOne is the builder for updating a single AccountPool entity.
type AccountPoolUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountPoolMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountPoolUpdateOne) SetUpdatedAt(v time.Time) *AccountPoolUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountPoolUpdateOne) SetName(v string) *AccountPoolUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountPoolUpdateOne) SetNillableName(v *string) *AccountPoolUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *AccountPoolUpdateOne) SetPlatform(v string) *AccountPoolUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *AccountPoolUpdateOne) SetNillablePlatform(v *string) *AccountPoolUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *AccountPoolUpdateOne) SetNotes(v string) *AccountPoolUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *AccountPoolUpdateOne) SetNillableNotes(v *string) *AccountPoolUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *AccountPoolUpdateOne) ClearNotes() *AccountPoolUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// Mutation returns the AccountPoolMutation object of the builder.
func (_u *AccountPoolUpdateOne) Mutation() *AccountPoolMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountPoolUpdate builder.
func (_u *AccountPoolUpdateOne) Where(ps ...predicate.AccountPool) *AccountPoolUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountPoolUpdateOne) Select(field string, fields ...string) *AccountPoolUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountPool entity.
func (_u *AccountPoolUpdateOne) Save(ctx context.Context) (*AccountPool, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountPoolUpdateOne) SaveX(ctx context.Context) *AccountPool {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountPoolUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountPoolUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountPoolUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountpool.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountPoolUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accountpool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountPool.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := accountpool.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "AccountPool.platform": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountPoolUpdateOne) sqlSave(ctx context.Context) (_node *AccountPool, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountpool.Table, accountpool.Columns, sqlgraph.NewFieldSpec(accountpool.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountPool.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountpool.FieldID)
		for _, f := range fields {
			if !accountpool.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountpool.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountpool.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accountpool.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(accountpool.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(accountpool.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(accountpool.FieldNotes, field.TypeString)
	}
	_node = &AccountPool{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountpool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
