// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountpool"
)

// AccountPoolCreate is the builder for creating a AccountPool entity.
type AccountPoolCreate struct {
	config
	mutation *AccountPoolMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountPoolCreate) SetCreatedAt(v time.Time) *AccountPoolCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountPoolCreate) SetNillableCreatedAt(v *time.Time) *AccountPoolCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountPoolCreate) SetUpdatedAt(v time.Time) *AccountPoolCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountPoolCreate) SetNillableUpdatedAt(v *time.Time) *AccountPoolCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AccountPoolCreate) SetName(v string) *AccountPoolCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *AccountPoolCreate) SetPlatform(v string) *AccountPoolCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *AccountPoolCreate) SetNotes(v string) *AccountPoolCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *AccountPoolCreate) SetNillableNotes(v *string) *AccountPoolCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// Mutation returns the AccountPoolMutation object of the builder.
func (_c *AccountPoolCreate) Mutation() *AccountPoolMutation {
	return _c.mutation
}

// Save creates the AccountPool in the database.
func (_c *AccountPoolCreate) Save(ctx context.Context) (*AccountPool, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountPoolCreate) SaveX(ctx context.Context) *AccountPool {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountPoolCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountPoolCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountPoolCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountpool.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountpool.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountPoolCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountPool.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountPool.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AccountPool.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := accountpool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountPool.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "AccountPool.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := accountpool.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "AccountPool.platform": %w`, err)}
		}
	}
	return nil
}

func (_c *AccountPoolCreate) sqlSave(ctx context.Context) (*AccountPool, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountPoolCreate) createSpec() (*AccountPool, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountPool{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountpool.Table, sqlgraph.NewFieldSpec(accountpool.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountpool.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountpool.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(accountpool.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(accountpool.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(accountpool.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountPool.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountPoolUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountPoolCreate) OnConflict(opts ...sql.ConflictOption) *AccountPoolUpsertOne {
	_c.conflict = opts
	return &AccountPoolUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountPool.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountPoolCreate) OnConflictColumns(columns ...string) *AccountPoolUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountPoolUpsertOne{
		create: _c,
	}
}

type (
	// AccountPoolUpsertOne is the builder for "upsert"-ing
	//  one AccountPool node.
	AccountPoolUpsertOne struct {
		create *AccountPoolCreate
	}

	// AccountPoolUpsert is the "OnConflict" setter.
	AccountPoolUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountPoolUpsert) SetUpdatedAt(v time.Time) *AccountPoolUpsert {
	u.Set(accountpool.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountPoolUpsert) UpdateUpdatedAt() *AccountPoolUpsert {
	u.SetExcluded(accountpool.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *AccountPoolUpsert) SetName(v string) *AccountPoolUpsert {
	u.Set(accountpool.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountPoolUpsert) UpdateName() *AccountPoolUpsert {
	u.SetExcluded(accountpool.FieldName)
	return u
}

// SetPlatform sets the "platform" field.
func (u *AccountPoolUpsert) SetPlatform(v string) *AccountPoolUpsert {
	u.Set(accountpool.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *AccountPoolUpsert) UpdatePlatform() *AccountPoolUpsert {
	u.SetExcluded(accountpool.FieldPlatform)
	return u
}

// SetNotes sets the "notes" field.
func (u *AccountPoolUpsert) SetNotes(v string) *AccountPoolUpsert {
	u.Set(accountpool.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *AccountPoolUpsert) UpdateNotes() *AccountPoolUpsert {
	u.SetExcluded(accountpool.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *AccountPoolUpsert) ClearNotes() *AccountPoolUpsert {
	u.SetNull(accountpool.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountPool.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountPoolUpsertOne) UpdateNewValues() *AccountPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountpool.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountPool.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountPoolUpsertOne) Ignore() *AccountPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountPoolUpsertOne) DoNothing() *AccountPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountPoolCreate.OnConflict
// documentation for more info.
func (u *AccountPoolUpsertOne) Update(set func(*AccountPoolUpsert)) *AccountPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountPoolUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountPoolUpsertOne) SetUpdatedAt(v time.Time) *AccountPoolUpsertOne {
	return u.Update(func(s *AccountPoolUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountPoolUpsertOne) UpdateUpdatedAt() *AccountPoolUpsertOne {
	return u.Update(func(s *AccountPoolUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *AccountPoolUpsertOne) SetName(v string) *AccountPoolUpsertOne {
	return u.Update(func(s *AccountPoolUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountPoolUpsertOne) UpdateName() *AccountPoolUpsertOne {
	return u.Update(func(s *AccountPoolUpsert) {
		s.UpdateName()
	})
}

// SetPlatform sets the "platform" field.
func (u *AccountPoolUpsertOne) SetPlatform(v string) *AccountPoolUpsertOne {
	return u.Update(func(s *AccountPoolUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *AccountPoolUpsertOne) UpdatePlatform() *AccountPoolUpsertOne {
	return u.Update(func(s *AccountPoolUpsert) {
		s.UpdatePlatform()
	})
}

// SetNotes sets the "notes" field.
func (u *AccountPoolUpsertOne) SetNotes(v string) *AccountPoolUpsertOne {
	return u.Update(func(s *AccountPoolUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *AccountPoolUpsertOne) UpdateNotes() *AccountPoolUpsertOne {
	return u.Update(func(s *AccountPoolUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *AccountPoolUpsertOne) ClearNotes() *AccountPoolUpsertOne {
	return u.Update(func(s *AccountPoolUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *AccountPoolUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountPoolCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountPoolUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountPoolUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountPoolUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountPoolCreateBulk is the builder for creating many AccountPool entities in bulk.
type AccountPoolCreateBulk struct {
	config
	err      error
	builders []*AccountPoolCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountPool entities in the database.
func (_c *AccountPoolCreateBulk) Save(ctx context.Context) ([]*AccountPool, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountPool, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountPoolMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountPoolCreateBulk) SaveX(ctx context.Context) []*AccountPool {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountPoolCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountPoolCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountPool.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountPoolUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountPoolCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountPoolUpsertBulk {
	_c.conflict = opts
	return &AccountPoolUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountPool.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountPoolCreateBulk) OnConflictColumns(columns ...string) *AccountPoolUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountPoolUpsertBulk{
		create: _c,
	}
}

// AccountPoolUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountPool nodes.
type AccountPoolUpsertBulk struct {
	create *AccountPoolCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountPool.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountPoolUpsertBulk) UpdateNewValues() *AccountPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountpool.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountPool.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountPoolUpsertBulk) Ignore() *AccountPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountPoolUpsertBulk) DoNothing() *AccountPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountPoolCreateBulk.OnConflict
// documentation for more info.
func (u *AccountPoolUpsertBulk) Update(set func(*AccountPoolUpsert)) *AccountPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountPoolUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountPoolUpsertBulk) SetUpdatedAt(v time.Time) *AccountPoolUpsertBulk {
	return u.Update(func(s *AccountPoolUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountPoolUpsertBulk) UpdateUpdatedAt() *AccountPoolUpsertBulk {
	return u.Update(func(s *AccountPoolUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *AccountPoolUpsertBulk) SetName(v string) *AccountPoolUpsertBulk {
	return u.Update(func(s *AccountPoolUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountPoolUpsertBulk) UpdateName() *AccountPoolUpsertBulk {
	return u.Update(func(s *AccountPoolUpsert) {
		s.UpdateName()
	})
}

// SetPlatform sets the "platform" field.
func (u *AccountPoolUpsertBulk) SetPlatform(v string) *AccountPoolUpsertBulk {
	return u.Update(func(s *AccountPoolUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *AccountPoolUpsertBulk) UpdatePlatform() *AccountPoolUpsertBulk {
	return u.Update(func(s *AccountPoolUpsert) {
		s.UpdatePlatform()
	})
}

// SetNotes sets the "notes" field.
func (u *AccountPoolUpsertBulk) SetNotes(v string) *AccountPoolUpsertBulk {
	return u.Update(func(s *AccountPoolUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *AccountPoolUpsertBulk) UpdateNotes() *AccountPoolUpsertBulk {
	return u.Update(func(s *AccountPoolUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *AccountPoolUpsertBulk) ClearNotes() *AccountPoolUpsertBulk {
	return u.Update(func(s *AccountPoolUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *AccountPoolUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountPoolCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountPoolCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountPoolUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
