// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentinvoicedocument"
	"github.com/Wei-Shaw/sub2api/ent/paymentinvoicerequest"
)

// PaymentInvoiceDocumentCreate is the builder for creating a PaymentInvoiceDocument entity.
type PaymentInvoiceDocumentCreate struct {
	config
	mutation *PaymentInvoiceDocumentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (_c *PaymentInvoiceDocumentCreate) SetInvoiceRequestID(v int64) *PaymentInvoiceDocumentCreate {
	_c.mutation.SetInvoiceRequestID(v)
	return _c
}

// SetFilename sets the "filename" field.
func (_c *PaymentInvoiceDocumentCreate) SetFilename(v string) *PaymentInvoiceDocumentCreate {
	_c.mutation.SetFilename(v)
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *PaymentInvoiceDocumentCreate) SetContentType(v string) *PaymentInvoiceDocumentCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_c *PaymentInvoiceDocumentCreate) SetNillableContentType(v *string) *PaymentInvoiceDocumentCreate {
	if v != nil {
		_c.SetContentType(*v)
	}
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *PaymentInvoiceDocumentCreate) SetSizeBytes(v int64) *PaymentInvoiceDocumentCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *PaymentInvoiceDocumentCreate) SetSha256(v string) *PaymentInvoiceDocumentCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetData sets the "data" field.
func (_c *PaymentInvoiceDocumentCreate) SetData(v []byte) *PaymentInvoiceDocumentCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentInvoiceDocumentCreate) SetCreatedAt(v time.Time) *PaymentInvoiceDocumentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentInvoiceDocumentCreate) SetNillableCreatedAt(v *time.Time) *PaymentInvoiceDocumentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentInvoiceDocumentCreate) SetUpdatedAt(v time.Time) *PaymentInvoiceDocumentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentInvoiceDocumentCreate) SetNillableUpdatedAt(v *time.Time) *PaymentInvoiceDocumentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetInvoiceRequest sets the "invoice_request" edge to the PaymentInvoiceRequest entity.
func (_c *PaymentInvoiceDocumentCreate) SetInvoiceRequest(v *PaymentInvoiceRequest) *PaymentInvoiceDocumentCreate {
	return _c.SetInvoiceRequestID(v.ID)
}

// Mutation returns the PaymentInvoiceDocumentMutation object of the builder.
func (_c *PaymentInvoiceDocumentCreate) Mutation() *PaymentInvoiceDocumentMutation {
	return _c.mutation
}

// Save creates the PaymentInvoiceDocument in the database.
func (_c *PaymentInvoiceDocumentCreate) Save(ctx context.Context) (*PaymentInvoiceDocument, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentInvoiceDocumentCreate) SaveX(ctx context.Context) *PaymentInvoiceDocument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentInvoiceDocumentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentInvoiceDocumentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentInvoiceDocumentCreate) defaults() {
	if _, ok := _c.mutation.ContentType(); !ok {
		v := paymentinvoicedocument.DefaultContentType
		_c.mutation.SetContentType(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentinvoicedocument.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paymentinvoicedocument.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentInvoiceDocumentCreate) check() error {
	if _, ok := _c.mutation.InvoiceRequestID(); !ok {
		return &ValidationError{Name: "invoice_request_id", err: errors.New(`ent: missing required field "PaymentInvoiceDocument.invoice_request_id"`)}
	}
	if _, ok := _c.mutation.Filename(); !ok {
		return &ValidationError{Name: "filename", err: errors.New(`ent: missing required field "PaymentInvoiceDocument.filename"`)}
	}
	if v, ok := _c.mutation.Filename(); ok {
		if err := paymentinvoicedocument.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoiceDocument.filename": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "PaymentInvoiceDocument.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := paymentinvoicedocument.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoiceDocument.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "PaymentInvoiceDocument.size_bytes"`)}
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`ent: missing required field "PaymentInvoiceDocument.sha256"`)}
	}
	if v, ok := _c.mutation.Sha256(); ok {
		if err := paymentinvoicedocument.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoiceDocument.sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "PaymentInvoiceDocument.data"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentInvoiceDocument.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentInvoiceDocument.updated_at"`)}
	}
	if len(_c.mutation.InvoiceRequestIDs()) == 0 {
		return &ValidationError{Name: "invoice_request", err: errors.New(`ent: missing required edge "PaymentInvoiceDocument.invoice_request"`)}
	}
	return nil
}

func (_c *PaymentInvoiceDocumentCreate) sqlSave(ctx context.Context) (*PaymentInvoiceDocument, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentInvoiceDocumentCreate) createSpec() (*PaymentInvoiceDocument, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentInvoiceDocument{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentinvoicedocument.Table, sqlgraph.NewFieldSpec(paymentinvoicedocument.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Filename(); ok {
		_spec.SetField(paymentinvoicedocument.FieldFilename, field.TypeString, value)
		_node.Filename = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(paymentinvoicedocument.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(paymentinvoicedocument.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(paymentinvoicedocument.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(paymentinvoicedocument.FieldData, field.TypeBytes, value)
		_node.Data = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentinvoicedocument.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentinvoicedocument.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.InvoiceRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paymentinvoicedocument.InvoiceRequestTable,
			Columns: []string{paymentinvoicedocument.InvoiceRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentinvoicerequest.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InvoiceRequestID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentInvoiceDocument.Create().
//		SetInvoiceRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentInvoiceDocumentUpsert) {
//			SetInvoiceRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentInvoiceDocumentCreate) OnConflict(opts ...sql.ConflictOption) *PaymentInvoiceDocumentUpsertOne {
	_c.conflict = opts
	return &PaymentInvoiceDocumentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentInvoiceDocument.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentInvoiceDocumentCreate) OnConflictColumns(columns ...string) *PaymentInvoiceDocumentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentInvoiceDocumentUpsertOne{
		create: _c,
	}
}

type (
	// PaymentInvoiceDocumentUpsertOne is the builder for "upsert"-ing
	//  one PaymentInvoiceDocument node.
	PaymentInvoiceDocumentUpsertOne struct {
		create *PaymentInvoiceDocumentCreate
	}

	// PaymentInvoiceDocumentUpsert is the "OnConflict" setter.
	PaymentInvoiceDocumentUpsert struct {
		*sql.UpdateSet
	}
)

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (u *PaymentInvoiceDocumentUpsert) SetInvoiceRequestID(v int64) *PaymentInvoiceDocumentUpsert {
	u.Set(paymentinvoicedocument.FieldInvoiceRequestID, v)
	return u
}

// UpdateInvoiceRequestID sets the "invoice_request_id" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsert) UpdateInvoiceRequestID() *PaymentInvoiceDocumentUpsert {
	u.SetExcluded(paymentinvoicedocument.FieldInvoiceRequestID)
	return u
}

// SetFilename sets the "filename" field.
func (u *PaymentInvoiceDocumentUpsert) SetFilename(v string) *PaymentInvoiceDocumentUpsert {
	u.Set(paymentinvoicedocument.FieldFilename, v)
	return u
}

// UpdateFilename sets the "filename" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsert) UpdateFilename() *PaymentInvoiceDocumentUpsert {
	u.SetExcluded(paymentinvoicedocument.FieldFilename)
	return u
}

// SetContentType sets the "content_type" field.
func (u *PaymentInvoiceDocumentUpsert) SetContentType(v string) *PaymentInvoiceDocumentUpsert {
	u.Set(paymentinvoicedocument.FieldContentType, v)
	return u
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsert) UpdateContentType() *PaymentInvoiceDocumentUpsert {
	u.SetExcluded(paymentinvoicedocument.FieldContentType)
	return u
}

// SetSizeBytes sets the "size_bytes" field.
func (u *PaymentInvoiceDocumentUpsert) SetSizeBytes(v int64) *PaymentInvoiceDocumentUpsert {
	u.Set(paymentinvoicedocument.FieldSizeBytes, v)
	return u
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsert) UpdateSizeBytes() *PaymentInvoiceDocumentUpsert {
	u.SetExcluded(paymentinvoicedocument.FieldSizeBytes)
	return u
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *PaymentInvoiceDocumentUpsert) AddSizeBytes(v int64) *PaymentInvoiceDocumentUpsert {
	u.Add(paymentinvoicedocument.FieldSizeBytes, v)
	return u
}

// SetSha256 sets the "sha256" field.
func (u *PaymentInvoiceDocumentUpsert) SetSha256(v string) *PaymentInvoiceDocumentUpsert {
	u.Set(paymentinvoicedocument.FieldSha256, v)
	return u
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsert) UpdateSha256() *PaymentInvoiceDocumentUpsert {
	u.SetExcluded(paymentinvoicedocument.FieldSha256)
	return u
}

// SetData sets the "data" field.
func (u *PaymentInvoiceDocumentUpsert) SetData(v []byte) *PaymentInvoiceDocumentUpsert {
	u.Set(paymentinvoicedocument.FieldData, v)
	return u
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsert) UpdateData() *PaymentInvoiceDocumentUpsert {
	u.SetExcluded(paymentinvoicedocument.FieldData)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentInvoiceDocumentUpsert) SetUpdatedAt(v time.Time) *PaymentInvoiceDocumentUpsert {
	u.Set(paymentinvoicedocument.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsert) UpdateUpdatedAt() *PaymentInvoiceDocumentUpsert {
	u.SetExcluded(paymentinvoicedocument.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentInvoiceDocument.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentInvoiceDocumentUpsertOne) UpdateNewValues() *PaymentInvoiceDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentinvoicedocument.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentInvoiceDocument.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentInvoiceDocumentUpsertOne) Ignore() *PaymentInvoiceDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentInvoiceDocumentUpsertOne) DoNothing() *PaymentInvoiceDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentInvoiceDocumentCreate.OnConflict
// documentation for more info.
func (u *PaymentInvoiceDocumentUpsertOne) Update(set func(*PaymentInvoiceDocumentUpsert)) *PaymentInvoiceDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentInvoiceDocumentUpsert{UpdateSet: update})
	}))
	return u
}

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (u *PaymentInvoiceDocumentUpsertOne) SetInvoiceRequestID(v int64) *PaymentInvoiceDocumentUpsertOne {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.SetInvoiceRequestID(v)
	})
}

// UpdateInvoiceRequestID sets the "invoice_request_id" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsertOne) UpdateInvoiceRequestID() *PaymentInvoiceDocumentUpsertOne {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.UpdateInvoiceRequestID()
	})
}

// SetFilename sets the "filename" field.
func (u *PaymentInvoiceDocumentUpsertOne) SetFilename(v string) *PaymentInvoiceDocumentUpsertOne {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.SetFilename(v)
	})
}

// UpdateFilename sets the "filename" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsertOne) UpdateFilename() *PaymentInvoiceDocumentUpsertOne {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.UpdateFilename()
	})
}

// SetContentType sets the "content_type" field.
func (u *PaymentInvoiceDocumentUpsertOne) SetContentType(v string) *PaymentInvoiceDocumentUpsertOne {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsertOne) UpdateContentType() *PaymentInvoiceDocumentUpsertOne {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.UpdateContentType()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *PaymentInvoiceDocumentUpsertOne) SetSizeBytes(v int64) *PaymentInvoiceDocumentUpsertOne {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *PaymentInvoiceDocumentUpsertOne) AddSizeBytes(v int64) *PaymentInvoiceDocumentUpsertOne {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsertOne) UpdateSizeBytes() *PaymentInvoiceDocumentUpsertOne {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetSha256 sets the "sha256" field.
func (u *PaymentInvoiceDocumentUpsertOne) SetSha256(v string) *PaymentInvoiceDocumentUpsertOne {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsertOne) UpdateSha256() *PaymentInvoiceDocumentUpsertOne {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.UpdateSha256()
	})
}

// SetData sets the "data" field.
func (u *PaymentInvoiceDocumentUpsertOne) SetData(v []byte) *PaymentInvoiceDocumentUpsertOne {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsertOne) UpdateData() *PaymentInvoiceDocumentUpsertOne {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.UpdateData()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentInvoiceDocumentUpsertOne) SetUpdatedAt(v time.Time) *PaymentInvoiceDocumentUpsertOne {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsertOne) UpdateUpdatedAt() *PaymentInvoiceDocumentUpsertOne {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentInvoiceDocumentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentInvoiceDocumentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentInvoiceDocumentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentInvoiceDocumentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentInvoiceDocumentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentInvoiceDocumentCreateBulk is the builder for creating many PaymentInvoiceDocument entities in bulk.
type PaymentInvoiceDocumentCreateBulk struct {
	config
	err      error
	builders []*PaymentInvoiceDocumentCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentInvoiceDocument entities in the database.
func (_c *PaymentInvoiceDocumentCreateBulk) Save(ctx context.Context) ([]*PaymentInvoiceDocument, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentInvoiceDocument, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentInvoiceDocumentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentInvoiceDocumentCreateBulk) SaveX(ctx context.Context) []*PaymentInvoiceDocument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentInvoiceDocumentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentInvoiceDocumentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentInvoiceDocument.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentInvoiceDocumentUpsert) {
//			SetInvoiceRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentInvoiceDocumentCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentInvoiceDocumentUpsertBulk {
	_c.conflict = opts
	return &PaymentInvoiceDocumentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentInvoiceDocument.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentInvoiceDocumentCreateBulk) OnConflictColumns(columns ...string) *PaymentInvoiceDocumentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentInvoiceDocumentUpsertBulk{
		create: _c,
	}
}

// PaymentInvoiceDocumentUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentInvoiceDocument nodes.
type PaymentInvoiceDocumentUpsertBulk struct {
	create *PaymentInvoiceDocumentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentInvoiceDocument.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentInvoiceDocumentUpsertBulk) UpdateNewValues() *PaymentInvoiceDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentinvoicedocument.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentInvoiceDocument.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentInvoiceDocumentUpsertBulk) Ignore() *PaymentInvoiceDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentInvoiceDocumentUpsertBulk) DoNothing() *PaymentInvoiceDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentInvoiceDocumentCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentInvoiceDocumentUpsertBulk) Update(set func(*PaymentInvoiceDocumentUpsert)) *PaymentInvoiceDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentInvoiceDocumentUpsert{UpdateSet: update})
	}))
	return u
}

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (u *PaymentInvoiceDocumentUpsertBulk) SetInvoiceRequestID(v int64) *PaymentInvoiceDocumentUpsertBulk {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.SetInvoiceRequestID(v)
	})
}

// UpdateInvoiceRequestID sets the "invoice_request_id" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsertBulk) UpdateInvoiceRequestID() *PaymentInvoiceDocumentUpsertBulk {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.UpdateInvoiceRequestID()
	})
}

// SetFilename sets the "filename" field.
func (u *PaymentInvoiceDocumentUpsertBulk) SetFilename(v string) *PaymentInvoiceDocumentUpsertBulk {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.SetFilename(v)
	})
}

// UpdateFilename sets the "filename" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsertBulk) UpdateFilename() *PaymentInvoiceDocumentUpsertBulk {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.UpdateFilename()
	})
}

// SetContentType sets the "content_type" field.
func (u *PaymentInvoiceDocumentUpsertBulk) SetContentType(v string) *PaymentInvoiceDocumentUpsertBulk {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsertBulk) UpdateContentType() *PaymentInvoiceDocumentUpsertBulk {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.UpdateContentType()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *PaymentInvoiceDocumentUpsertBulk) SetSizeBytes(v int64) *PaymentInvoiceDocumentUpsertBulk {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *PaymentInvoiceDocumentUpsertBulk) AddSizeBytes(v int64) *PaymentInvoiceDocumentUpsertBulk {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsertBulk) UpdateSizeBytes() *PaymentInvoiceDocumentUpsertBulk {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetSha256 sets the "sha256" field.
func (u *PaymentInvoiceDocumentUpsertBulk) SetSha256(v string) *PaymentInvoiceDocumentUpsertBulk {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsertBulk) UpdateSha256() *PaymentInvoiceDocumentUpsertBulk {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.UpdateSha256()
	})
}

// SetData sets the "data" field.
func (u *PaymentInvoiceDocumentUpsertBulk) SetData(v []byte) *PaymentInvoiceDocumentUpsertBulk {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsertBulk) UpdateData() *PaymentInvoiceDocumentUpsertBulk {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.UpdateData()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentInvoiceDocumentUpsertBulk) SetUpdatedAt(v time.Time) *PaymentInvoiceDocumentUpsertBulk {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentInvoiceDocumentUpsertBulk) UpdateUpdatedAt() *PaymentInvoiceDocumentUpsertBulk {
	return u.Update(func(s *PaymentInvoiceDocumentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentInvoiceDocumentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentInvoiceDocumentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentInvoiceDocumentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentInvoiceDocumentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
