// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentinvoicedocument"
	"github.com/Wei-Shaw/sub2api/ent/paymentinvoicerequest"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentInvoiceDocumentUpdate is the builder for updating PaymentInvoiceDocument entities.
type PaymentInvoiceDocumentUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentInvoiceDocumentMutation
}

// Where appends a list predicates to the PaymentInvoiceDocumentUpdate builder.
func (_u *PaymentInvoiceDocumentUpdate) Where(ps ...predicate.PaymentInvoiceDocument) *PaymentInvoiceDocumentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (_u *PaymentInvoiceDocumentUpdate) SetInvoiceRequestID(v int64) *PaymentInvoiceDocumentUpdate {
	_u.mutation.SetInvoiceRequestID(v)
	return _u
}

// SetNillableInvoiceRequestID sets the "invoice_request_id" field if the given value is not nil.
func (_u *PaymentInvoiceDocumentUpdate) SetNillableInvoiceRequestID(v *int64) *PaymentInvoiceDocumentUpdate {
	if v != nil {
		_u.SetInvoiceRequestID(*v)
	}
	return _u
}

// SetFilename sets the "filename" field.
func (_u *PaymentInvoiceDocumentUpdate) SetFilename(v string) *PaymentInvoiceDocumentUpdate {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *PaymentInvoiceDocumentUpdate) SetNillableFilename(v *string) *PaymentInvoiceDocumentUpdate {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *PaymentInvoiceDocumentUpdate) SetContentType(v string) *PaymentInvoiceDocumentUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *PaymentInvoiceDocumentUpdate) SetNillableContentType(v *string) *PaymentInvoiceDocumentUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *PaymentInvoiceDocumentUpdate) SetSizeBytes(v int64) *PaymentInvoiceDocumentUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *PaymentInvoiceDocumentUpdate) SetNillableSizeBytes(v *int64) *PaymentInvoiceDocumentUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *PaymentInvoiceDocumentUpdate) AddSizeBytes(v int64) *PaymentInvoiceDocumentUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *PaymentInvoiceDocumentUpdate) SetSha256(v string) *PaymentInvoiceDocumentUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *PaymentInvoiceDocumentUpdate) SetNillableSha256(v *string) *PaymentInvoiceDocumentUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetData sets the "data" field.
func (_u *PaymentInvoiceDocumentUpdate) SetData(v []byte) *PaymentInvoiceDocumentUpdate {
	_u.mutation.SetData(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentInvoiceDocumentUpdate) SetUpdatedAt(v time.Time) *PaymentInvoiceDocumentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetInvoiceRequest sets the "invoice_request" edge to the PaymentInvoiceRequest entity.
func (_u *PaymentInvoiceDocumentUpdate) SetInvoiceRequest(v *PaymentInvoiceRequest) *PaymentInvoiceDocumentUpdate {
	return _u.SetInvoiceRequestID(v.ID)
}

// Mutation returns the PaymentInvoiceDocumentMutation object of the builder.
func (_u *PaymentInvoiceDocumentUpdate) Mutation() *PaymentInvoiceDocumentMutation {
	return _u.mutation
}

// ClearInvoiceRequest clears the "invoice_request" edge to the PaymentInvoiceRequest entity.
func (_u *PaymentInvoiceDocumentUpdate) ClearInvoiceRequest() *PaymentInvoiceDocumentUpdate {
	_u.mutation.ClearInvoiceRequest()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentInvoiceDocumentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentInvoiceDocumentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentInvoiceDocumentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentInvoiceDocumentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentInvoiceDocumentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentinvoicedocument.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentInvoiceDocumentUpdate) check() error {
	if v, ok := _u.mutation.Filename(); ok {
		if err := paymentinvoicedocument.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoiceDocument.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := paymentinvoicedocument.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoiceDocument.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := paymentinvoicedocument.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoiceDocument.sha256": %w`, err)}
		}
	}
	if _u.mutation.InvoiceRequestCleared() && len(_u.mutation.InvoiceRequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentInvoiceDocument.invoice_request"`)
	}
	return nil
}

func (_u *PaymentInvoiceDocumentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentinvoicedocument.Table, paymentinvoicedocument.Columns, sqlgraph.NewFieldSpec(paymentinvoicedocument.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(paymentinvoicedocument.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(paymentinvoicedocument.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(paymentinvoicedocument.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(paymentinvoicedocument.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(paymentinvoicedocument.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(paymentinvoicedocument.FieldData, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentinvoicedocument.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.InvoiceRequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paymentinvoicedocument.InvoiceRequestTable,
			Columns: []string{paymentinvoicedocument.InvoiceRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentinvoicerequest.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvoiceRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paymentinvoicedocument.InvoiceRequestTable,
			Columns: []string{paymentinvoicedocument.InvoiceRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentinvoicerequest.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentinvoicedocument.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentInvoiceDocumentUpdateOne is the builder for updating a single PaymentInvoiceDocument entity.
type PaymentInvoiceDocumentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentInvoiceDocumentMutation
}

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (_u *PaymentInvoiceDocumentUpdateOne) SetInvoiceRequestID(v int64) *PaymentInvoiceDocumentUpdateOne {
	_u.mutation.SetInvoiceRequestID(v)
	return _u
}

// SetNillableInvoiceRequestID sets the "invoice_request_id" field if the given value is not nil.
func (_u *PaymentInvoiceDocumentUpdateOne) SetNillableInvoiceRequestID(v *int64) *PaymentInvoiceDocumentUpdateOne {
	if v != nil {
		_u.SetInvoiceRequestID(*v)
	}
	return _u
}

// SetFilename sets the "filename" field.
func (_u *PaymentInvoiceDocumentUpdateOne) SetFilename(v string) *PaymentInvoiceDocumentUpdateOne {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *PaymentInvoiceDocumentUpdateOne) SetNillableFilename(v *string) *PaymentInvoiceDocumentUpdateOne {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *PaymentInvoiceDocumentUpdateOne) SetContentType(v string) *PaymentInvoiceDocumentUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *PaymentInvoiceDocumentUpdateOne) SetNillableContentType(v *string) *PaymentInvoiceDocumentUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *PaymentInvoiceDocumentUpdateOne) SetSizeBytes(v int64) *PaymentInvoiceDocumentUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *PaymentInvoiceDocumentUpdateOne) SetNillableSizeBytes(v *int64) *PaymentInvoiceDocumentUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *PaymentInvoiceDocumentUpdateOne) AddSizeBytes(v int64) *PaymentInvoiceDocumentUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *PaymentInvoiceDocumentUpdateOne) SetSha256(v string) *PaymentInvoiceDocumentUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *PaymentInvoiceDocumentUpdateOne) SetNillableSha256(v *string) *PaymentInvoiceDocumentUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetData sets the "data" field.
func (_u *PaymentInvoiceDocumentUpdateOne) SetData(v []byte) *PaymentInvoiceDocumentUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentInvoiceDocumentUpdateOne) SetUpdatedAt(v time.Time) *PaymentInvoiceDocumentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetInvoiceRequest sets the "invoice_request" edge to the PaymentInvoiceRequest entity.
func (_u *PaymentInvoiceDocumentUpdateOne) SetInvoiceRequest(v *PaymentInvoiceRequest) *PaymentInvoiceDocumentUpdateOne {
	return _u.SetInvoiceRequestID(v.ID)
}

// Mutation returns the PaymentInvoiceDocumentMutation object of the builder.
func (_u *PaymentInvoiceDocumentUpdateOne) Mutation() *PaymentInvoiceDocumentMutation {
	return _u.mutation
}

// ClearInvoiceRequest clears the "invoice_request" edge to the PaymentInvoiceRequest entity.
func (_u *PaymentInvoiceDocumentUpdateOne) ClearInvoiceRequest() *PaymentInvoiceDocumentUpdateOne {
	_u.mutation.ClearInvoiceRequest()
	return _u
}

// Where appends a list predicates to the PaymentInvoiceDocumentUpdate builder.
func (_u *PaymentInvoiceDocumentUpdateOne) Where(ps ...predicate.PaymentInvoiceDocument) *PaymentInvoiceDocumentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentInvoiceDocumentUpdateOne) Select(field string, fields ...string) *PaymentInvoiceDocumentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentInvoiceDocument entity.
func (_u *PaymentInvoiceDocumentUpdateOne) Save(ctx context.Context) (*PaymentInvoiceDocument, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentInvoiceDocumentUpdateOne) SaveX(ctx context.Context) *PaymentInvoiceDocument {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentInvoiceDocumentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentInvoiceDocumentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentInvoiceDocumentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentinvoicedocument.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentInvoiceDocumentUpdateOne) check() error {
	if v, ok := _u.mutation.Filename(); ok {
		if err := paymentinvoicedocument.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoiceDocument.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := paymentinvoicedocument.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoiceDocument.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := paymentinvoicedocument.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "PaymentInvoiceDocument.sha256": %w`, err)}
		}
	}
	if _u.mutation.InvoiceRequestCleared() && len(_u.mutation.InvoiceRequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentInvoiceDocument.invoice_request"`)
	}
	return nil
}

func (_u *PaymentInvoiceDocumentUpdateOne) sqlSave(ctx context.Context) (_node *PaymentInvoiceDocument, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentinvoicedocument.Table, paymentinvoicedocument.Columns, sqlgraph.NewFieldSpec(paymentinvoicedocument.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentInvoiceDocument.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentinvoicedocument.FieldID)
		for _, f := range fields {
			if !paymentinvoicedocument.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentinvoicedocument.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(paymentinvoicedocument.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(paymentinvoicedocument.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(paymentinvoicedocument.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(paymentinvoicedocument.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(paymentinvoicedocument.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(paymentinvoicedocument.FieldData, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentinvoicedocument.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.InvoiceRequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paymentinvoicedocument.InvoiceRequestTable,
			Columns: []string{paymentinvoicedocument.InvoiceRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentinvoicerequest.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvoiceRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paymentinvoicedocument.InvoiceRequestTable,
			Columns: []string{paymentinvoicedocument.InvoiceRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentinvoicerequest.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentInvoiceDocument{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentinvoicedocument.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
