// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentinvoicedocument"
	"github.com/Wei-Shaw/sub2api/ent/paymentinvoicerequest"
)

// PaymentInvoiceDocument is the model entity for the PaymentInvoiceDocument schema.
type PaymentInvoiceDocument struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// InvoiceRequestID holds the value of the "invoice_request_id" field.
	InvoiceRequestID int64 `json:"invoice_request_id,omitempty"`
	// Filename holds the value of the "filename" field.
	Filename string `json:"filename,omitempty"`
	// ContentType holds the value of the "content_type" field.
	ContentType string `json:"content_type,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// Sha256 holds the value of the "sha256" field.
	Sha256 string `json:"sha256,omitempty"`
	// Data holds the value of the "data" field.
	Data []byte `json:"-"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentInvoiceDocumentQuery when eager-loading is set.
	Edges        PaymentInvoiceDocumentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PaymentInvoiceDocumentEdges holds the relations/edges for other nodes in the graph.
type PaymentInvoiceDocumentEdges struct {
	// InvoiceRequest holds the value of the invoice_request edge.
	InvoiceRequest *PaymentInvoiceRequest `json:"invoice_request,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// InvoiceRequestOrErr returns the InvoiceRequest value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentInvoiceDocumentEdges) InvoiceRequestOrErr() (*PaymentInvoiceRequest, error) {
	if e.InvoiceRequest != nil {
		return e.InvoiceRequest, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: paymentinvoicerequest.Label}
	}
	return nil, &NotLoadedError{edge: "invoice_request"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentInvoiceDocument) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentinvoicedocument.FieldData:
			values[i] = new([]byte)
		case paymentinvoicedocument.FieldID, paymentinvoicedocument.FieldInvoiceRequestID, paymentinvoicedocument.FieldSizeBytes:
			values[i] = new(sql.NullInt64)
		case paymentinvoicedocument.FieldFilename, paymentinvoicedocument.FieldContentType, paymentinvoicedocument.FieldSha256:
			values[i] = new(sql.NullString)
		case paymentinvoicedocument.FieldCreatedAt, paymentinvoicedocument.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentInvoiceDocument fields.
func (_m *PaymentInvoiceDocument) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentinvoicedocument.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymentinvoicedocument.FieldInvoiceRequestID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_request_id", values[i])
			} else if value.Valid {
				_m.InvoiceRequestID = value.Int64
			}
		case paymentinvoicedocument.FieldFilename:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field filename", values[i])
			} else if value.Valid {
				_m.Filename = value.String
			}
		case paymentinvoicedocument.FieldContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value.Valid {
				_m.ContentType = value.String
			}
		case paymentinvoicedocument.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				_m.SizeBytes = value.Int64
			}
		case paymentinvoicedocument.FieldSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha256", values[i])
			} else if value.Valid {
				_m.Sha256 = value.String
			}
		case paymentinvoicedocument.FieldData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value != nil {
				_m.Data = *value
			}
		case paymentinvoicedocument.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentinvoicedocument.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentInvoiceDocument.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentInvoiceDocument) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInvoiceRequest queries the "invoice_request" edge of the PaymentInvoiceDocument entity.
func (_m *PaymentInvoiceDocument) QueryInvoiceRequest() *PaymentInvoiceRequestQuery {
	return NewPaymentInvoiceDocumentClient(_m.config).QueryInvoiceRequest(_m)
}

// Update returns a builder for updating this PaymentInvoiceDocument.
// Note that you need to call PaymentInvoiceDocument.Unwrap() before calling this method if this PaymentInvoiceDocument
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentInvoiceDocument) Update() *PaymentInvoiceDocumentUpdateOne {
	return NewPaymentInvoiceDocumentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentInvoiceDocument entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentInvoiceDocument) Unwrap() *PaymentInvoiceDocument {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentInvoiceDocument is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentInvoiceDocument) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentInvoiceDocument(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("invoice_request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InvoiceRequestID))
	builder.WriteString(", ")
	builder.WriteString("filename=")
	builder.WriteString(_m.Filename)
	builder.WriteString(", ")
	builder.WriteString("content_type=")
	builder.WriteString(_m.ContentType)
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeBytes))
	builder.WriteString(", ")
	builder.WriteString("sha256=")
	builder.WriteString(_m.Sha256)
	builder.WriteString(", ")
	builder.WriteString("data=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentInvoiceDocuments is a parsable slice of PaymentInvoiceDocument.
type PaymentInvoiceDocuments []*PaymentInvoiceDocument
