// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentinvoicedocument"
	"github.com/Wei-Shaw/sub2api/ent/paymentinvoicerequest"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
)

// PaymentInvoiceRequest is the model entity for the PaymentInvoiceRequest schema.
type PaymentInvoiceRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID int64 `json:"order_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// TitleType holds the value of the "title_type" field.
	TitleType string `json:"title_type,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// TaxIdentifier holds the value of the "tax_identifier" field.
	TaxIdentifier *string `json:"-"`
	// RecipientEmail holds the value of the "recipient_email" field.
	RecipientEmail string `json:"-"`
	// RecipientPhone holds the value of the "recipient_phone" field.
	RecipientPhone *string `json:"-"`
	// Remark holds the value of the "remark" field.
	Remark *string `json:"remark,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Revision holds the value of the "revision" field.
	Revision int `json:"revision,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// ProviderInvoiceID holds the value of the "provider_invoice_id" field.
	ProviderInvoiceID *string `json:"provider_invoice_id,omitempty"`
	// InvoiceItemName holds the value of the "invoice_item_name" field.
	InvoiceItemName *string `json:"invoice_item_name,omitempty"`
	// InvoiceCode holds the value of the "invoice_code" field.
	InvoiceCode *string `json:"invoice_code,omitempty"`
	// InvoiceNumber holds the value of the "invoice_number" field.
	InvoiceNumber *string `json:"invoice_number,omitempty"`
	// DocumentFilename holds the value of the "document_filename" field.
	DocumentFilename *string `json:"document_filename,omitempty"`
	// DocumentSizeBytes holds the value of the "document_size_bytes" field.
	DocumentSizeBytes *int64 `json:"document_size_bytes,omitempty"`
	// DocumentSha256 holds the value of the "document_sha256" field.
	DocumentSha256 *string `json:"document_sha256,omitempty"`
	// EmailDeliveryStatus holds the value of the "email_delivery_status" field.
	EmailDeliveryStatus string `json:"email_delivery_status,omitempty"`
	// EmailDeliveryAttempts holds the value of the "email_delivery_attempts" field.
	EmailDeliveryAttempts int `json:"email_delivery_attempts,omitempty"`
	// EmailDeliveryErrorKind holds the value of the "email_delivery_error_kind" field.
	EmailDeliveryErrorKind *string `json:"email_delivery_error_kind,omitempty"`
	// EmailDeliveryAttemptedAt holds the value of the "email_delivery_attempted_at" field.
	EmailDeliveryAttemptedAt *time.Time `json:"email_delivery_attempted_at,omitempty"`
	// EmailDeliveredAt holds the value of the "email_delivered_at" field.
	EmailDeliveredAt *time.Time `json:"email_delivered_at,omitempty"`
	// EmailDeliveryClaimToken holds the value of the "email_delivery_claim_token" field.
	EmailDeliveryClaimToken *string `json:"email_delivery_claim_token,omitempty"`
	// EmailDeliveryClaimedAt holds the value of the "email_delivery_claimed_at" field.
	EmailDeliveryClaimedAt *time.Time `json:"email_delivery_claimed_at,omitempty"`
	// EmailDeliveryNextAttemptAt holds the value of the "email_delivery_next_attempt_at" field.
	EmailDeliveryNextAttemptAt *time.Time `json:"email_delivery_next_attempt_at,omitempty"`
	// FeishuNotificationStatus holds the value of the "feishu_notification_status" field.
	FeishuNotificationStatus string `json:"feishu_notification_status,omitempty"`
	// FeishuNotificationRevision holds the value of the "feishu_notification_revision" field.
	FeishuNotificationRevision int `json:"feishu_notification_revision,omitempty"`
	// FeishuNotificationAttempts holds the value of the "feishu_notification_attempts" field.
	FeishuNotificationAttempts int `json:"feishu_notification_attempts,omitempty"`
	// FeishuNotificationErrorKind holds the value of the "feishu_notification_error_kind" field.
	FeishuNotificationErrorKind *string `json:"feishu_notification_error_kind,omitempty"`
	// FeishuNotificationAttemptedAt holds the value of the "feishu_notification_attempted_at" field.
	FeishuNotificationAttemptedAt *time.Time `json:"feishu_notification_attempted_at,omitempty"`
	// FeishuNotifiedAt holds the value of the "feishu_notified_at" field.
	FeishuNotifiedAt *time.Time `json:"feishu_notified_at,omitempty"`
	// FeishuNotificationClaimToken holds the value of the "feishu_notification_claim_token" field.
	FeishuNotificationClaimToken *string `json:"feishu_notification_claim_token,omitempty"`
	// FeishuNotificationClaimedAt holds the value of the "feishu_notification_claimed_at" field.
	FeishuNotificationClaimedAt *time.Time `json:"feishu_notification_claimed_at,omitempty"`
	// FeishuNotificationNextAttemptAt holds the value of the "feishu_notification_next_attempt_at" field.
	FeishuNotificationNextAttemptAt *time.Time `json:"feishu_notification_next_attempt_at,omitempty"`
	// RejectionReason holds the value of the "rejection_reason" field.
	RejectionReason *string `json:"rejection_reason,omitempty"`
	// ProcessedBy holds the value of the "processed_by" field.
	ProcessedBy *int64 `json:"processed_by,omitempty"`
	// RequestedAt holds the value of the "requested_at" field.
	RequestedAt time.Time `json:"requested_at,omitempty"`
	// ProcessedAt holds the value of the "processed_at" field.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`
	// IssuedAt holds the value of the "issued_at" field.
	IssuedAt *time.Time `json:"issued_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentInvoiceRequestQuery when eager-loading is set.
	Edges        PaymentInvoiceRequestEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PaymentInvoiceRequestEdges holds the relations/edges for other nodes in the graph.
type PaymentInvoiceRequestEdges struct {
	// Order holds the value of the order edge.
	Order *PaymentOrder `json:"order,omitempty"`
	// Document holds the value of the document edge.
	Document *PaymentInvoiceDocument `json:"document,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OrderOrErr returns the Order value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentInvoiceRequestEdges) OrderOrErr() (*PaymentOrder, error) {
	if e.Order != nil {
		return e.Order, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: paymentorder.Label}
	}
	return nil, &NotLoadedError{edge: "order"}
}

// DocumentOrErr returns the Document value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentInvoiceRequestEdges) DocumentOrErr() (*PaymentInvoiceDocument, error) {
	if e.Document != nil {
		return e.Document, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: paymentinvoicedocument.Label}
	}
	return nil, &NotLoadedError{edge: "document"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentInvoiceRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentinvoicerequest.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case paymentinvoicerequest.FieldID, paymentinvoicerequest.FieldOrderID, paymentinvoicerequest.FieldUserID, paymentinvoicerequest.FieldRevision, paymentinvoicerequest.FieldDocumentSizeBytes, paymentinvoicerequest.FieldEmailDeliveryAttempts, paymentinvoicerequest.FieldFeishuNotificationRevision, paymentinvoicerequest.FieldFeishuNotificationAttempts, paymentinvoicerequest.FieldProcessedBy:
			values[i] = new(sql.NullInt64)
		case paymentinvoicerequest.FieldTitleType, paymentinvoicerequest.FieldTitle, paymentinvoicerequest.FieldTaxIdentifier, paymentinvoicerequest.FieldRecipientEmail, paymentinvoicerequest.FieldRecipientPhone, paymentinvoicerequest.FieldRemark, paymentinvoicerequest.FieldCurrency, paymentinvoicerequest.FieldStatus, paymentinvoicerequest.FieldProvider, paymentinvoicerequest.FieldProviderInvoiceID, paymentinvoicerequest.FieldInvoiceItemName, paymentinvoicerequest.FieldInvoiceCode, paymentinvoicerequest.FieldInvoiceNumber, paymentinvoicerequest.FieldDocumentFilename, paymentinvoicerequest.FieldDocumentSha256, paymentinvoicerequest.FieldEmailDeliveryStatus, paymentinvoicerequest.FieldEmailDeliveryErrorKind, paymentinvoicerequest.FieldEmailDeliveryClaimToken, paymentinvoicerequest.FieldFeishuNotificationStatus, paymentinvoicerequest.FieldFeishuNotificationErrorKind, paymentinvoicerequest.FieldFeishuNotificationClaimToken, paymentinvoicerequest.FieldRejectionReason:
			values[i] = new(sql.NullString)
		case paymentinvoicerequest.FieldEmailDeliveryAttemptedAt, paymentinvoicerequest.FieldEmailDeliveredAt, paymentinvoicerequest.FieldEmailDeliveryClaimedAt, paymentinvoicerequest.FieldEmailDeliveryNextAttemptAt, paymentinvoicerequest.FieldFeishuNotificationAttemptedAt, paymentinvoicerequest.FieldFeishuNotifiedAt, paymentinvoicerequest.FieldFeishuNotificationClaimedAt, paymentinvoicerequest.FieldFeishuNotificationNextAttemptAt, paymentinvoicerequest.FieldRequestedAt, paymentinvoicerequest.FieldProcessedAt, paymentinvoicerequest.FieldIssuedAt, paymentinvoicerequest.FieldCreatedAt, paymentinvoicerequest.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentInvoiceRequest fields.
func (_m *PaymentInvoiceRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentinvoicerequest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymentinvoicerequest.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.Int64
			}
		case paymentinvoicerequest.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case paymentinvoicerequest.FieldTitleType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title_type", values[i])
			} else if value.Valid {
				_m.TitleType = value.String
			}
		case paymentinvoicerequest.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case paymentinvoicerequest.FieldTaxIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_identifier", values[i])
			} else if value.Valid {
				_m.TaxIdentifier = new(string)
				*_m.TaxIdentifier = value.String
			}
		case paymentinvoicerequest.FieldRecipientEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient_email", values[i])
			} else if value.Valid {
				_m.RecipientEmail = value.String
			}
		case paymentinvoicerequest.FieldRecipientPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient_phone", values[i])
			} else if value.Valid {
				_m.RecipientPhone = new(string)
				*_m.RecipientPhone = value.String
			}
		case paymentinvoicerequest.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = new(string)
				*_m.Remark = value.String
			}
		case paymentinvoicerequest.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case paymentinvoicerequest.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case paymentinvoicerequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case paymentinvoicerequest.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = int(value.Int64)
			}
		case paymentinvoicerequest.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case paymentinvoicerequest.FieldProviderInvoiceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_invoice_id", values[i])
			} else if value.Valid {
				_m.ProviderInvoiceID = new(string)
				*_m.ProviderInvoiceID = value.String
			}
		case paymentinvoicerequest.FieldInvoiceItemName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_item_name", values[i])
			} else if value.Valid {
				_m.InvoiceItemName = new(string)
				*_m.InvoiceItemName = value.String
			}
		case paymentinvoicerequest.FieldInvoiceCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_code", values[i])
			} else if value.Valid {
				_m.InvoiceCode = new(string)
				*_m.InvoiceCode = value.String
			}
		case paymentinvoicerequest.FieldInvoiceNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_number", values[i])
			} else if value.Valid {
				_m.InvoiceNumber = new(string)
				*_m.InvoiceNumber = value.String
			}
		case paymentinvoicerequest.FieldDocumentFilename:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field document_filename", values[i])
			} else if value.Valid {
				_m.DocumentFilename = new(string)
				*_m.DocumentFilename = value.String
			}
		case paymentinvoicerequest.FieldDocumentSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field document_size_bytes", values[i])
			} else if value.Valid {
				_m.DocumentSizeBytes = new(int64)
				*_m.DocumentSizeBytes = value.Int64
			}
		case paymentinvoicerequest.FieldDocumentSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field document_sha256", values[i])
			} else if value.Valid {
				_m.DocumentSha256 = new(string)
				*_m.DocumentSha256 = value.String
			}
		case paymentinvoicerequest.FieldEmailDeliveryStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email_delivery_status", values[i])
			} else if value.Valid {
				_m.EmailDeliveryStatus = value.String
			}
		case paymentinvoicerequest.FieldEmailDeliveryAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field email_delivery_attempts", values[i])
			} else if value.Valid {
				_m.EmailDeliveryAttempts = int(value.Int64)
			}
		case paymentinvoicerequest.FieldEmailDeliveryErrorKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email_delivery_error_kind", values[i])
			} else if value.Valid {
				_m.EmailDeliveryErrorKind = new(string)
				*_m.EmailDeliveryErrorKind = value.String
			}
		case paymentinvoicerequest.FieldEmailDeliveryAttemptedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field email_delivery_attempted_at", values[i])
			} else if value.Valid {
				_m.EmailDeliveryAttemptedAt = new(time.Time)
				*_m.EmailDeliveryAttemptedAt = value.Time
			}
		case paymentinvoicerequest.FieldEmailDeliveredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field email_delivered_at", values[i])
			} else if value.Valid {
				_m.EmailDeliveredAt = new(time.Time)
				*_m.EmailDeliveredAt = value.Time
			}
		case paymentinvoicerequest.FieldEmailDeliveryClaimToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email_delivery_claim_token", values[i])
			} else if value.Valid {
				_m.EmailDeliveryClaimToken = new(string)
				*_m.EmailDeliveryClaimToken = value.String
			}
		case paymentinvoicerequest.FieldEmailDeliveryClaimedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field email_delivery_claimed_at", values[i])
			} else if value.Valid {
				_m.EmailDeliveryClaimedAt = new(time.Time)
				*_m.EmailDeliveryClaimedAt = value.Time
			}
		case paymentinvoicerequest.FieldEmailDeliveryNextAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field email_delivery_next_attempt_at", values[i])
			} else if value.Valid {
				_m.EmailDeliveryNextAttemptAt = new(time.Time)
				*_m.EmailDeliveryNextAttemptAt = value.Time
			}
		case paymentinvoicerequest.FieldFeishuNotificationStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field feishu_notification_status", values[i])
			} else if value.Valid {
				_m.FeishuNotificationStatus = value.String
			}
		case paymentinvoicerequest.FieldFeishuNotificationRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field feishu_notification_revision", values[i])
			} else if value.Valid {
				_m.FeishuNotificationRevision = int(value.Int64)
			}
		case paymentinvoicerequest.FieldFeishuNotificationAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field feishu_notification_attempts", values[i])
			} else if value.Valid {
				_m.FeishuNotificationAttempts = int(value.Int64)
			}
		case paymentinvoicerequest.FieldFeishuNotificationErrorKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field feishu_notification_error_kind", values[i])
			} else if value.Valid {
				_m.FeishuNotificationErrorKind = new(string)
				*_m.FeishuNotificationErrorKind = value.String
			}
		case paymentinvoicerequest.FieldFeishuNotificationAttemptedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field feishu_notification_attempted_at", values[i])
			} else if value.Valid {
				_m.FeishuNotificationAttemptedAt = new(time.Time)
				*_m.FeishuNotificationAttemptedAt = value.Time
			}
		case paymentinvoicerequest.FieldFeishuNotifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field feishu_notified_at", values[i])
			} else if value.Valid {
				_m.FeishuNotifiedAt = new(time.Time)
				*_m.FeishuNotifiedAt = value.Time
			}
		case paymentinvoicerequest.FieldFeishuNotificationClaimToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field feishu_notification_claim_token", values[i])
			} else if value.Valid {
				_m.FeishuNotificationClaimToken = new(string)
				*_m.FeishuNotificationClaimToken = value.String
			}
		case paymentinvoicerequest.FieldFeishuNotificationClaimedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field feishu_notification_claimed_at", values[i])
			} else if value.Valid {
				_m.FeishuNotificationClaimedAt = new(time.Time)
				*_m.FeishuNotificationClaimedAt = value.Time
			}
		case paymentinvoicerequest.FieldFeishuNotificationNextAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field feishu_notification_next_attempt_at", values[i])
			} else if value.Valid {
				_m.FeishuNotificationNextAttemptAt = new(time.Time)
				*_m.FeishuNotificationNextAttemptAt = value.Time
			}
		case paymentinvoicerequest.FieldRejectionReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rejection_reason", values[i])
			} else if value.Valid {
				_m.RejectionReason = new(string)
				*_m.RejectionReason = value.String
			}
		case paymentinvoicerequest.FieldProcessedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field processed_by", values[i])
			} else if value.Valid {
				_m.ProcessedBy = new(int64)
				*_m.ProcessedBy = value.Int64
			}
		case paymentinvoicerequest.FieldRequestedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field requested_at", values[i])
			} else if value.Valid {
				_m.RequestedAt = value.Time
			}
		case paymentinvoicerequest.FieldProcessedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field processed_at", values[i])
			} else if value.Valid {
				_m.ProcessedAt = new(time.Time)
				*_m.ProcessedAt = value.Time
			}
		case paymentinvoicerequest.FieldIssuedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field issued_at", values[i])
			} else if value.Valid {
				_m.IssuedAt = new(time.Time)
				*_m.IssuedAt = value.Time
			}
		case paymentinvoicerequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentinvoicerequest.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentInvoiceRequest.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentInvoiceRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOrder queries the "order" edge of the PaymentInvoiceRequest entity.
func (_m *PaymentInvoiceRequest) QueryOrder() *PaymentOrderQuery {
	return NewPaymentInvoiceRequestClient(_m.config).QueryOrder(_m)
}

// QueryDocument queries the "document" edge of the PaymentInvoiceRequest entity.
func (_m *PaymentInvoiceRequest) QueryDocument() *PaymentInvoiceDocumentQuery {
	return NewPaymentInvoiceRequestClient(_m.config).QueryDocument(_m)
}

// Update returns a builder for updating this PaymentInvoiceRequest.
// Note that you need to call PaymentInvoiceRequest.Unwrap() before calling this method if this PaymentInvoiceRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentInvoiceRequest) Update() *PaymentInvoiceRequestUpdateOne {
	return NewPaymentInvoiceRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentInvoiceRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentInvoiceRequest) Unwrap() *PaymentInvoiceRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentInvoiceRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentInvoiceRequest) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentInvoiceRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("title_type=")
	builder.WriteString(_m.TitleType)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("tax_identifier=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("recipient_email=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("recipient_phone=<sensitive>")
	builder.WriteString(", ")
	if v := _m.Remark; v != nil {
		builder.WriteString("remark=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	if v := _m.ProviderInvoiceID; v != nil {
		builder.WriteString("provider_invoice_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.InvoiceItemName; v != nil {
		builder.WriteString("invoice_item_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.InvoiceCode; v != nil {
		builder.WriteString("invoice_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.InvoiceNumber; v != nil {
		builder.WriteString("invoice_number=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DocumentFilename; v != nil {
		builder.WriteString("document_filename=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DocumentSizeBytes; v != nil {
		builder.WriteString("document_size_bytes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DocumentSha256; v != nil {
		builder.WriteString("document_sha256=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("email_delivery_status=")
	builder.WriteString(_m.EmailDeliveryStatus)
	builder.WriteString(", ")
	builder.WriteString("email_delivery_attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmailDeliveryAttempts))
	builder.WriteString(", ")
	if v := _m.EmailDeliveryErrorKind; v != nil {
		builder.WriteString("email_delivery_error_kind=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.EmailDeliveryAttemptedAt; v != nil {
		builder.WriteString("email_delivery_attempted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EmailDeliveredAt; v != nil {
		builder.WriteString("email_delivered_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EmailDeliveryClaimToken; v != nil {
		builder.WriteString("email_delivery_claim_token=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.EmailDeliveryClaimedAt; v != nil {
		builder.WriteString("email_delivery_claimed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EmailDeliveryNextAttemptAt; v != nil {
		builder.WriteString("email_delivery_next_attempt_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("feishu_notification_status=")
	builder.WriteString(_m.FeishuNotificationStatus)
	builder.WriteString(", ")
	builder.WriteString("feishu_notification_revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeishuNotificationRevision))
	builder.WriteString(", ")
	builder.WriteString("feishu_notification_attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeishuNotificationAttempts))
	builder.WriteString(", ")
	if v := _m.FeishuNotificationErrorKind; v != nil {
		builder.WriteString("feishu_notification_error_kind=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FeishuNotificationAttemptedAt; v != nil {
		builder.WriteString("feishu_notification_attempted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FeishuNotifiedAt; v != nil {
		builder.WriteString("feishu_notified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FeishuNotificationClaimToken; v != nil {
		builder.WriteString("feishu_notification_claim_token=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FeishuNotificationClaimedAt; v != nil {
		builder.WriteString("feishu_notification_claimed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FeishuNotificationNextAttemptAt; v != nil {
		builder.WriteString("feishu_notification_next_attempt_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RejectionReason; v != nil {
		builder.WriteString("rejection_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProcessedBy; v != nil {
		builder.WriteString("processed_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("requested_at=")
	builder.WriteString(_m.RequestedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ProcessedAt; v != nil {
		builder.WriteString("processed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.IssuedAt; v != nil {
		builder.WriteString("issued_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentInvoiceRequests is a parsable slice of PaymentInvoiceRequest.
type PaymentInvoiceRequests []*PaymentInvoiceRequest
