// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentinvoicerequest"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentInvoiceRequestDelete is the builder for deleting a PaymentInvoiceRequest entity.
type PaymentInvoiceRequestDelete struct {
	config
	hooks    []Hook
	mutation *PaymentInvoiceRequestMutation
}

// Where appends a list predicates to the PaymentInvoiceRequestDelete builder.
func (_d *PaymentInvoiceRequestDelete) Where(ps ...predicate.PaymentInvoiceRequest) *PaymentInvoiceRequestDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PaymentInvoiceRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentInvoiceRequestDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PaymentInvoiceRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(paymentinvoicerequest.Table, sqlgraph.NewFieldSpec(paymentinvoicerequest.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PaymentInvoiceRequestDeleteOne is the builder for deleting a single PaymentInvoiceRequest entity.
type PaymentInvoiceRequestDeleteOne struct {
	_d *PaymentInvoiceRequestDelete
}

// Where appends a list predicates to the PaymentInvoiceRequestDelete builder.
func (_d *PaymentInvoiceRequestDeleteOne) Where(ps ...predicate.PaymentInvoiceRequest) *PaymentInvoiceRequestDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PaymentInvoiceRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{paymentinvoicerequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentInvoiceRequestDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
