// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentinvoicedocument"
	"github.com/Wei-Shaw/sub2api/ent/paymentinvoicerequest"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentInvoiceRequestQuery is the builder for querying PaymentInvoiceRequest entities.
type PaymentInvoiceRequestQuery struct {
	config
	ctx          *QueryContext
	order        []paymentinvoicerequest.OrderOption
	inters       []Interceptor
	predicates   []predicate.PaymentInvoiceRequest
	withOrder    *PaymentOrderQuery
	withDocument *PaymentInvoiceDocumentQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PaymentInvoiceRequestQuery builder.
func (_q *PaymentInvoiceRequestQuery) Where(ps ...predicate.PaymentInvoiceRequest) *PaymentInvoiceRequestQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PaymentInvoiceRequestQuery) Limit(limit int) *PaymentInvoiceRequestQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PaymentInvoiceRequestQuery) Offset(offset int) *PaymentInvoiceRequestQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PaymentInvoiceRequestQuery) Unique(unique bool) *PaymentInvoiceRequestQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PaymentInvoiceRequestQuery) Order(o ...paymentinvoicerequest.OrderOption) *PaymentInvoiceRequestQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryOrder chains the current query on the "order" edge.
func (_q *PaymentInvoiceRequestQuery) QueryOrder() *PaymentOrderQuery {
	query := (&PaymentOrderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(paymentinvoicerequest.Table, paymentinvoicerequest.FieldID, selector),
			sqlgraph.To(paymentorder.Table, paymentorder.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, paymentinvoicerequest.OrderTable, paymentinvoicerequest.OrderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDocument chains the current query on the "document" edge.
func (_q *PaymentInvoiceRequestQuery) QueryDocument() *PaymentInvoiceDocumentQuery {
	query := (&PaymentInvoiceDocumentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(paymentinvoicerequest.Table, paymentinvoicerequest.FieldID, selector),
			sqlgraph.To(paymentinvoicedocument.Table, paymentinvoicedocument.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, paymentinvoicerequest.DocumentTable, paymentinvoicerequest.DocumentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PaymentInvoiceRequest entity from the query.
// Returns a *NotFoundError when no PaymentInvoiceRequest was found.
func (_q *PaymentInvoiceRequestQuery) First(ctx context.Context) (*PaymentInvoiceRequest, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{paymentinvoicerequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PaymentInvoiceRequestQuery) FirstX(ctx context.Context) *PaymentInvoiceRequest {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PaymentInvoiceRequest ID from the query.
// Returns a *NotFoundError when no PaymentInvoiceRequest ID was found.
func (_q *PaymentInvoiceRequestQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{paymentinvoicerequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PaymentInvoiceRequestQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PaymentInvoiceRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PaymentInvoiceRequest entity is found.
// Returns a *NotFoundError when no PaymentInvoiceRequest entities are found.
func (_q *PaymentInvoiceRequestQuery) Only(ctx context.Context) (*PaymentInvoiceRequest, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{paymentinvoicerequest.Label}
	default:
		return nil, &NotSingularError{paymentinvoicerequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PaymentInvoiceRequestQuery) OnlyX(ctx context.Context) *PaymentInvoiceRequest {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PaymentInvoiceRequest ID in the query.
// Returns a *NotSingularError when more than one PaymentInvoiceRequest ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PaymentInvoiceRequestQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{paymentinvoicerequest.Label}
	default:
		err = &NotSingularError{paymentinvoicerequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PaymentInvoiceRequestQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PaymentInvoiceRequests.
func (_q *PaymentInvoiceRequestQuery) All(ctx context.Context) ([]*PaymentInvoiceRequest, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PaymentInvoiceRequest, *PaymentInvoiceRequestQuery]()
	return withInterceptors[[]*PaymentInvoiceRequest](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PaymentInvoiceRequestQuery) AllX(ctx context.Context) []*PaymentInvoiceRequest {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PaymentInvoiceRequest IDs.
func (_q *PaymentInvoiceRequestQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(paymentinvoicerequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PaymentInvoiceRequestQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PaymentInvoiceRequestQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PaymentInvoiceRequestQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PaymentInvoiceRequestQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PaymentInvoiceRequestQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PaymentInvoiceRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PaymentInvoiceRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PaymentInvoiceRequestQuery) Clone() *PaymentInvoiceRequestQuery {
	if _q == nil {
		return nil
	}
	return &PaymentInvoiceRequestQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]paymentinvoicerequest.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.PaymentInvoiceRequest{}, _q.predicates...),
		withOrder:    _q.withOrder.Clone(),
		withDocument: _q.withDocument.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithOrder tells the query-builder to eager-load the nodes that are connected to
// the "order" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PaymentInvoiceRequestQuery) WithOrder(opts ...func(*PaymentOrderQuery)) *PaymentInvoiceRequestQuery {
	query := (&PaymentOrderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOrder = query
	return _q
}

// WithDocument tells the query-builder to eager-load the nodes that are connected to
// the "document" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PaymentInvoiceRequestQuery) WithDocument(opts ...func(*PaymentInvoiceDocumentQuery)) *PaymentInvoiceRequestQuery {
	query := (&PaymentInvoiceDocumentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDocument = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OrderID int64 `json:"order_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PaymentInvoiceRequest.Query().
//		GroupBy(paymentinvoicerequest.FieldOrderID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PaymentInvoiceRequestQuery) GroupBy(field string, fields ...string) *PaymentInvoiceRequestGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PaymentInvoiceRequestGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = paymentinvoicerequest.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OrderID int64 `json:"order_id,omitempty"`
//	}
//
//	client.PaymentInvoiceRequest.Query().
//		Select(paymentinvoicerequest.FieldOrderID).
//		Scan(ctx, &v)
func (_q *PaymentInvoiceRequestQuery) Select(fields ...string) *PaymentInvoiceRequestSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PaymentInvoiceRequestSelect{PaymentInvoiceRequestQuery: _q}
	sbuild.label = paymentinvoicerequest.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PaymentInvoiceRequestSelect configured with the given aggregations.
func (_q *PaymentInvoiceRequestQuery) Aggregate(fns ...AggregateFunc) *PaymentInvoiceRequestSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PaymentInvoiceRequestQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !paymentinvoicerequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PaymentInvoiceRequestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PaymentInvoiceRequest, error) {
	var (
		nodes       = []*PaymentInvoiceRequest{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withOrder != nil,
			_q.withDocument != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PaymentInvoiceRequest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PaymentInvoiceRequest{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withOrder; query != nil {
		if err := _q.loadOrder(ctx, query, nodes, nil,
			func(n *PaymentInvoiceRequest, e *PaymentOrder) { n.Edges.Order = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDocument; query != nil {
		if err := _q.loadDocument(ctx, query, nodes, nil,
			func(n *PaymentInvoiceRequest, e *PaymentInvoiceDocument) { n.Edges.Document = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PaymentInvoiceRequestQuery) loadOrder(ctx context.Context, query *PaymentOrderQuery, nodes []*PaymentInvoiceRequest, init func(*PaymentInvoiceRequest), assign func(*PaymentInvoiceRequest, *PaymentOrder)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*PaymentInvoiceRequest)
	for i := range nodes {
		fk := nodes[i].OrderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(paymentorder.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "order_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PaymentInvoiceRequestQuery) loadDocument(ctx context.Context, query *PaymentInvoiceDocumentQuery, nodes []*PaymentInvoiceRequest, init func(*PaymentInvoiceRequest), assign func(*PaymentInvoiceRequest, *PaymentInvoiceDocument)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*PaymentInvoiceRequest)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(paymentinvoicedocument.FieldInvoiceRequestID)
	}
	query.Where(predicate.PaymentInvoiceDocument(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(paymentinvoicerequest.DocumentColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.InvoiceRequestID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "invoice_request_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *PaymentInvoiceRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PaymentInvoiceRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(paymentinvoicerequest.Table, paymentinvoicerequest.Columns, sqlgraph.NewFieldSpec(paymentinvoicerequest.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentinvoicerequest.FieldID)
		for i := range fields {
			if fields[i] != paymentinvoicerequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withOrder != nil {
			_spec.Node.AddColumnOnce(paymentinvoicerequest.FieldOrderID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PaymentInvoiceRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(paymentinvoicerequest.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = paymentinvoicerequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *PaymentInvoiceRequestQuery) ForUpdate(opts ...sql.LockOption) *PaymentInvoiceRequestQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *PaymentInvoiceRequestQuery) ForShare(opts ...sql.LockOption) *PaymentInvoiceRequestQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// PaymentInvoiceRequestGroupBy is the group-by builder for PaymentInvoiceRequest entities.
type PaymentInvoiceRequestGroupBy struct {
	selector
	build *PaymentInvoiceRequestQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PaymentInvoiceRequestGroupBy) Aggregate(fns ...AggregateFunc) *PaymentInvoiceRequestGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PaymentInvoiceRequestGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PaymentInvoiceRequestQuery, *PaymentInvoiceRequestGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PaymentInvoiceRequestGroupBy) sqlScan(ctx context.Context, root *PaymentInvoiceRequestQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PaymentInvoiceRequestSelect is the builder for selecting fields of PaymentInvoiceRequest entities.
type PaymentInvoiceRequestSelect struct {
	*PaymentInvoiceRequestQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PaymentInvoiceRequestSelect) Aggregate(fns ...AggregateFunc) *PaymentInvoiceRequestSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PaymentInvoiceRequestSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PaymentInvoiceRequestQuery, *PaymentInvoiceRequestSelect](ctx, _s.PaymentInvoiceRequestQuery, _s, _s.inters, v)
}

func (_s *PaymentInvoiceRequestSelect) sqlScan(ctx context.Context, root *PaymentInvoiceRequestQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
