// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
	"github.com/Wei-Shaw/sub2api/ent/proxypool"
)

// ProxyPoolCreate is the builder for creating a ProxyPool entity.
type ProxyPoolCreate struct {
	config
	mutation *ProxyPoolMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxyPoolCreate) SetCreatedAt(v time.Time) *ProxyPoolCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxyPoolCreate) SetNillableCreatedAt(v *time.Time) *ProxyPoolCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxyPoolCreate) SetUpdatedAt(v time.Time) *ProxyPoolCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxyPoolCreate) SetNillableUpdatedAt(v *time.Time) *ProxyPoolCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ProxyPoolCreate) SetName(v string) *ProxyPoolCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *ProxyPoolCreate) SetNotes(v string) *ProxyPoolCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *ProxyPoolCreate) SetNillableNotes(v *string) *ProxyPoolCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// AddProxyIDs adds the "proxies" edge to the Proxy entity by IDs.
func (_c *ProxyPoolCreate) AddProxyIDs(ids ...int64) *ProxyPoolCreate {
	_c.mutation.AddProxyIDs(ids...)
	return _c
}

// AddProxies adds the "proxies" edges to the Proxy entity.
func (_c *ProxyPoolCreate) AddProxies(v ...*Proxy) *ProxyPoolCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProxyIDs(ids...)
}

// Mutation returns the ProxyPoolMutation object of the builder.
func (_c *ProxyPoolCreate) Mutation() *ProxyPoolMutation {
	return _c.mutation
}

// Save creates the ProxyPool in the database.
func (_c *ProxyPoolCreate) Save(ctx context.Context) (*ProxyPool, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxyPoolCreate) SaveX(ctx context.Context) *ProxyPool {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyPoolCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyPoolCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxyPoolCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := proxypool.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := proxypool.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxyPoolCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxyPool.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxyPool.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ProxyPool.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := proxypool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxyPool.name": %w`, err)}
		}
	}
	return nil
}

func (_c *ProxyPoolCreate) sqlSave(ctx context.Context) (*ProxyPool, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxyPoolCreate) createSpec() (*ProxyPool, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxyPool{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxypool.Table, sqlgraph.NewFieldSpec(proxypool.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxypool.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxypool.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(proxypool.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(proxypool.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if nodes := _c.mutation.ProxiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxypool.ProxiesTable,
			Columns: []string{proxypool.ProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxyPool.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyPoolUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyPoolCreate) OnConflict(opts ...sql.ConflictOption) *ProxyPoolUpsertOne {
	_c.conflict = opts
	return &ProxyPoolUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxyPool.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyPoolCreate) OnConflictColumns(columns ...string) *ProxyPoolUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyPoolUpsertOne{
		create: _c,
	}
}

type (
	// ProxyPoolUpsertOne is the builder for "upsert"-ing
	//  one ProxyPool node.
	ProxyPoolUpsertOne struct {
		create *ProxyPoolCreate
	}

	// ProxyPoolUpsert is the "OnConflict" setter.
	ProxyPoolUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyPoolUpsert) SetUpdatedAt(v time.Time) *ProxyPoolUpsert {
	u.Set(proxypool.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyPoolUpsert) UpdateUpdatedAt() *ProxyPoolUpsert {
	u.SetExcluded(proxypool.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *ProxyPoolUpsert) SetName(v string) *ProxyPoolUpsert {
	u.Set(proxypool.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxyPoolUpsert) UpdateName() *ProxyPoolUpsert {
	u.SetExcluded(proxypool.FieldName)
	return u
}

// SetNotes sets the "notes" field.
func (u *ProxyPoolUpsert) SetNotes(v string) *ProxyPoolUpsert {
	u.Set(proxypool.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ProxyPoolUpsert) UpdateNotes() *ProxyPoolUpsert {
	u.SetExcluded(proxypool.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *ProxyPoolUpsert) ClearNotes() *ProxyPoolUpsert {
	u.SetNull(proxypool.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProxyPool.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxyPoolUpsertOne) UpdateNewValues() *ProxyPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(proxypool.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxyPool.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProxyPoolUpsertOne) Ignore() *ProxyPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyPoolUpsertOne) DoNothing() *ProxyPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyPoolCreate.OnConflict
// documentation for more info.
func (u *ProxyPoolUpsertOne) Update(set func(*ProxyPoolUpsert)) *ProxyPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyPoolUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyPoolUpsertOne) SetUpdatedAt(v time.Time) *ProxyPoolUpsertOne {
	return u.Update(func(s *ProxyPoolUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyPoolUpsertOne) UpdateUpdatedAt() *ProxyPoolUpsertOne {
	return u.Update(func(s *ProxyPoolUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *ProxyPoolUpsertOne) SetName(v string) *ProxyPoolUpsertOne {
	return u.Update(func(s *ProxyPoolUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxyPoolUpsertOne) UpdateName() *ProxyPoolUpsertOne {
	return u.Update(func(s *ProxyPoolUpsert) {
		s.UpdateName()
	})
}

// SetNotes sets the "notes" field.
func (u *ProxyPoolUpsertOne) SetNotes(v string) *ProxyPoolUpsertOne {
	return u.Update(func(s *ProxyPoolUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ProxyPoolUpsertOne) UpdateNotes() *ProxyPoolUpsertOne {
	return u.Update(func(s *ProxyPoolUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *ProxyPoolUpsertOne) ClearNotes() *ProxyPoolUpsertOne {
	return u.Update(func(s *ProxyPoolUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *ProxyPoolUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyPoolCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyPoolUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProxyPoolUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProxyPoolUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProxyPoolCreateBulk is the builder for creating many ProxyPool entities in bulk.
type ProxyPoolCreateBulk struct {
	config
	err      error
	builders []*ProxyPoolCreate
	conflict []sql.ConflictOption
}

// Save creates the ProxyPool entities in the database.
func (_c *ProxyPoolCreateBulk) Save(ctx context.Context) ([]*ProxyPool, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxyPool, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxyPoolMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxyPoolCreateBulk) SaveX(ctx context.Context) []*ProxyPool {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyPoolCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyPoolCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxyPool.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyPoolUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyPoolCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProxyPoolUpsertBulk {
	_c.conflict = opts
	return &ProxyPoolUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxyPool.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyPoolCreateBulk) OnConflictColumns(columns ...string) *ProxyPoolUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyPoolUpsertBulk{
		create: _c,
	}
}

// ProxyPoolUpsertBulk is the builder for "upsert"-ing
// a bulk of ProxyPool nodes.
type ProxyPoolUpsertBulk struct {
	create *ProxyPoolCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProxyPool.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxyPoolUpsertBulk) UpdateNewValues() *ProxyPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(proxypool.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxyPool.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProxyPoolUpsertBulk) Ignore() *ProxyPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyPoolUpsertBulk) DoNothing() *ProxyPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyPoolCreateBulk.OnConflict
// documentation for more info.
func (u *ProxyPoolUpsertBulk) Update(set func(*ProxyPoolUpsert)) *ProxyPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyPoolUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyPoolUpsertBulk) SetUpdatedAt(v time.Time) *ProxyPoolUpsertBulk {
	return u.Update(func(s *ProxyPoolUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyPoolUpsertBulk) UpdateUpdatedAt() *ProxyPoolUpsertBulk {
	return u.Update(func(s *ProxyPoolUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *ProxyPoolUpsertBulk) SetName(v string) *ProxyPoolUpsertBulk {
	return u.Update(func(s *ProxyPoolUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxyPoolUpsertBulk) UpdateName() *ProxyPoolUpsertBulk {
	return u.Update(func(s *ProxyPoolUpsert) {
		s.UpdateName()
	})
}

// SetNotes sets the "notes" field.
func (u *ProxyPoolUpsertBulk) SetNotes(v string) *ProxyPoolUpsertBulk {
	return u.Update(func(s *ProxyPoolUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ProxyPoolUpsertBulk) UpdateNotes() *ProxyPoolUpsertBulk {
	return u.Update(func(s *ProxyPoolUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *ProxyPoolUpsertBulk) ClearNotes() *ProxyPoolUpsertBulk {
	return u.Update(func(s *ProxyPoolUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *ProxyPoolUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProxyPoolCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyPoolCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyPoolUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
