// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/proxypool"
)

// ProxyPool is the model entity for the ProxyPool schema.
type ProxyPool struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProxyPoolQuery when eager-loading is set.
	Edges        ProxyPoolEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProxyPoolEdges holds the relations/edges for other nodes in the graph.
type ProxyPoolEdges struct {
	// Proxies holds the value of the proxies edge.
	Proxies []*Proxy `json:"proxies,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProxiesOrErr returns the Proxies value or an error if the edge
// was not loaded in eager-loading.
func (e ProxyPoolEdges) ProxiesOrErr() ([]*Proxy, error) {
	if e.loadedTypes[0] {
		return e.Proxies, nil
	}
	return nil, &NotLoadedError{edge: "proxies"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProxyPool) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxypool.FieldID:
			values[i] = new(sql.NullInt64)
		case proxypool.FieldName, proxypool.FieldNotes:
			values[i] = new(sql.NullString)
		case proxypool.FieldCreatedAt, proxypool.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProxyPool fields.
func (_m *ProxyPool) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxypool.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case proxypool.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxypool.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case proxypool.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case proxypool.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProxyPool.
// This includes values selected through modifiers, order, etc.
func (_m *ProxyPool) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProxies queries the "proxies" edge of the ProxyPool entity.
func (_m *ProxyPool) QueryProxies() *ProxyQuery {
	return NewProxyPoolClient(_m.config).QueryProxies(_m)
}

// Update returns a builder for updating this ProxyPool.
// Note that you need to call ProxyPool.Unwrap() before calling this method if this ProxyPool
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProxyPool) Update() *ProxyPoolUpdateOne {
	return NewProxyPoolClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProxyPool entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProxyPool) Unwrap() *ProxyPool {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProxyPool is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProxyPool) String() string {
	var builder strings.Builder
	builder.WriteString("ProxyPool(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ProxyPools is a parsable slice of ProxyPool.
type ProxyPools []*ProxyPool
