// Code generated by ent, DO NOT EDIT.

package paymentinvoicerequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the paymentinvoicerequest type in the database.
	Label = "payment_invoice_request"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldTitleType holds the string denoting the title_type field in the database.
	FieldTitleType = "title_type"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldTaxIdentifier holds the string denoting the tax_identifier field in the database.
	FieldTaxIdentifier = "tax_identifier"
	// FieldRecipientEmail holds the string denoting the recipient_email field in the database.
	FieldRecipientEmail = "recipient_email"
	// FieldRecipientPhone holds the string denoting the recipient_phone field in the database.
	FieldRecipientPhone = "recipient_phone"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRevision holds the string denoting the revision field in the database.
	FieldRevision = "revision"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldProviderInvoiceID holds the string denoting the provider_invoice_id field in the database.
	FieldProviderInvoiceID = "provider_invoice_id"
	// FieldInvoiceItemName holds the string denoting the invoice_item_name field in the database.
	FieldInvoiceItemName = "invoice_item_name"
	// FieldInvoiceCode holds the string denoting the invoice_code field in the database.
	FieldInvoiceCode = "invoice_code"
	// FieldInvoiceNumber holds the string denoting the invoice_number field in the database.
	FieldInvoiceNumber = "invoice_number"
	// FieldDocumentFilename holds the string denoting the document_filename field in the database.
	FieldDocumentFilename = "document_filename"
	// FieldDocumentSizeBytes holds the string denoting the document_size_bytes field in the database.
	FieldDocumentSizeBytes = "document_size_bytes"
	// FieldDocumentSha256 holds the string denoting the document_sha256 field in the database.
	FieldDocumentSha256 = "document_sha256"
	// FieldEmailDeliveryStatus holds the string denoting the email_delivery_status field in the database.
	FieldEmailDeliveryStatus = "email_delivery_status"
	// FieldEmailDeliveryAttempts holds the string denoting the email_delivery_attempts field in the database.
	FieldEmailDeliveryAttempts = "email_delivery_attempts"
	// FieldEmailDeliveryErrorKind holds the string denoting the email_delivery_error_kind field in the database.
	FieldEmailDeliveryErrorKind = "email_delivery_error_kind"
	// FieldEmailDeliveryAttemptedAt holds the string denoting the email_delivery_attempted_at field in the database.
	FieldEmailDeliveryAttemptedAt = "email_delivery_attempted_at"
	// FieldEmailDeliveredAt holds the string denoting the email_delivered_at field in the database.
	FieldEmailDeliveredAt = "email_delivered_at"
	// FieldEmailDeliveryClaimToken holds the string denoting the email_delivery_claim_token field in the database.
	FieldEmailDeliveryClaimToken = "email_delivery_claim_token"
	// FieldEmailDeliveryClaimedAt holds the string denoting the email_delivery_claimed_at field in the database.
	FieldEmailDeliveryClaimedAt = "email_delivery_claimed_at"
	// FieldEmailDeliveryNextAttemptAt holds the string denoting the email_delivery_next_attempt_at field in the database.
	FieldEmailDeliveryNextAttemptAt = "email_delivery_next_attempt_at"
	// FieldFeishuNotificationStatus holds the string denoting the feishu_notification_status field in the database.
	FieldFeishuNotificationStatus = "feishu_notification_status"
	// FieldFeishuNotificationRevision holds the string denoting the feishu_notification_revision field in the database.
	FieldFeishuNotificationRevision = "feishu_notification_revision"
	// FieldFeishuNotificationAttempts holds the string denoting the feishu_notification_attempts field in the database.
	FieldFeishuNotificationAttempts = "feishu_notification_attempts"
	// FieldFeishuNotificationErrorKind holds the string denoting the feishu_notification_error_kind field in the database.
	FieldFeishuNotificationErrorKind = "feishu_notification_error_kind"
	// FieldFeishuNotificationAttemptedAt holds the string denoting the feishu_notification_attempted_at field in the database.
	FieldFeishuNotificationAttemptedAt = "feishu_notification_attempted_at"
	// FieldFeishuNotifiedAt holds the string denoting the feishu_notified_at field in the database.
	FieldFeishuNotifiedAt = "feishu_notified_at"
	// FieldFeishuNotificationClaimToken holds the string denoting the feishu_notification_claim_token field in the database.
	FieldFeishuNotificationClaimToken = "feishu_notification_claim_token"
	// FieldFeishuNotificationClaimedAt holds the string denoting the feishu_notification_claimed_at field in the database.
	FieldFeishuNotificationClaimedAt = "feishu_notification_claimed_at"
	// FieldFeishuNotificationNextAttemptAt holds the string denoting the feishu_notification_next_attempt_at field in the database.
	FieldFeishuNotificationNextAttemptAt = "feishu_notification_next_attempt_at"
	// FieldRejectionReason holds the string denoting the rejection_reason field in the database.
	FieldRejectionReason = "rejection_reason"
	// FieldProcessedBy holds the string denoting the processed_by field in the database.
	FieldProcessedBy = "processed_by"
	// FieldRequestedAt holds the string denoting the requested_at field in the database.
	FieldRequestedAt = "requested_at"
	// FieldProcessedAt holds the string denoting the processed_at field in the database.
	FieldProcessedAt = "processed_at"
	// FieldIssuedAt holds the string denoting the issued_at field in the database.
	FieldIssuedAt = "issued_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOrder holds the string denoting the order edge name in mutations.
	EdgeOrder = "order"
	// EdgeDocument holds the string denoting the document edge name in mutations.
	EdgeDocument = "document"
	// Table holds the table name of the paymentinvoicerequest in the database.
	Table = "payment_invoice_requests"
	// OrderTable is the table that holds the order relation/edge.
	OrderTable = "payment_invoice_requests"
	// OrderInverseTable is the table name for the PaymentOrder entity.
	// It exists in this package in order to avoid circular dependency with the "paymentorder" package.
	OrderInverseTable = "payment_orders"
	// OrderColumn is the table column denoting the order relation/edge.
	OrderColumn = "order_id"
	// DocumentTable is the table that holds the document relation/edge.
	DocumentTable = "payment_invoice_documents"
	// DocumentInverseTable is the table name for the PaymentInvoiceDocument entity.
	// It exists in this package in order to avoid circular dependency with the "paymentinvoicedocument" package.
	DocumentInverseTable = "payment_invoice_documents"
	// DocumentColumn is the table column denoting the document relation/edge.
	DocumentColumn = "invoice_request_id"
)

// Columns holds all SQL columns for paymentinvoicerequest fields.
var Columns = []string{
	FieldID,
	FieldOrderID,
	FieldUserID,
	FieldTitleType,
	FieldTitle,
	FieldTaxIdentifier,
	FieldRecipientEmail,
	FieldRecipientPhone,
	FieldRemark,
	FieldAmount,
	FieldCurrency,
	FieldStatus,
	FieldRevision,
	FieldProvider,
	FieldProviderInvoiceID,
	FieldInvoiceItemName,
	FieldInvoiceCode,
	FieldInvoiceNumber,
	FieldDocumentFilename,
	FieldDocumentSizeBytes,
	FieldDocumentSha256,
	FieldEmailDeliveryStatus,
	FieldEmailDeliveryAttempts,
	FieldEmailDeliveryErrorKind,
	FieldEmailDeliveryAttemptedAt,
	FieldEmailDeliveredAt,
	FieldEmailDeliveryClaimToken,
	FieldEmailDeliveryClaimedAt,
	FieldEmailDeliveryNextAttemptAt,
	FieldFeishuNotificationStatus,
	FieldFeishuNotificationRevision,
	FieldFeishuNotificationAttempts,
	FieldFeishuNotificationErrorKind,
	FieldFeishuNotificationAttemptedAt,
	FieldFeishuNotifiedAt,
	FieldFeishuNotificationClaimToken,
	FieldFeishuNotificationClaimedAt,
	FieldFeishuNotificationNextAttemptAt,
	FieldRejectionReason,
	FieldProcessedBy,
	FieldRequestedAt,
	FieldProcessedAt,
	FieldIssuedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleTypeValidator is a validator for the "title_type" field. It is called by the builders before save.
	TitleTypeValidator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// TaxIdentifierValidator is a validator for the "tax_identifier" field. It is called by the builders before save.
	TaxIdentifierValidator func(string) error
	// RecipientEmailValidator is a validator for the "recipient_email" field. It is called by the builders before save.
	RecipientEmailValidator func(string) error
	// RecipientPhoneValidator is a validator for the "recipient_phone" field. It is called by the builders before save.
	RecipientPhoneValidator func(string) error
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultRevision holds the default value on creation for the "revision" field.
	DefaultRevision int
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// ProviderInvoiceIDValidator is a validator for the "provider_invoice_id" field. It is called by the builders before save.
	ProviderInvoiceIDValidator func(string) error
	// InvoiceItemNameValidator is a validator for the "invoice_item_name" field. It is called by the builders before save.
	InvoiceItemNameValidator func(string) error
	// InvoiceCodeValidator is a validator for the "invoice_code" field. It is called by the builders before save.
	InvoiceCodeValidator func(string) error
	// InvoiceNumberValidator is a validator for the "invoice_number" field. It is called by the builders before save.
	InvoiceNumberValidator func(string) error
	// DocumentFilenameValidator is a validator for the "document_filename" field. It is called by the builders before save.
	DocumentFilenameValidator func(string) error
	// DocumentSha256Validator is a validator for the "document_sha256" field. It is called by the builders before save.
	DocumentSha256Validator func(string) error
	// DefaultEmailDeliveryStatus holds the default value on creation for the "email_delivery_status" field.
	DefaultEmailDeliveryStatus string
	// EmailDeliveryStatusValidator is a validator for the "email_delivery_status" field. It is called by the builders before save.
	EmailDeliveryStatusValidator func(string) error
	// DefaultEmailDeliveryAttempts holds the default value on creation for the "email_delivery_attempts" field.
	DefaultEmailDeliveryAttempts int
	// EmailDeliveryErrorKindValidator is a validator for the "email_delivery_error_kind" field. It is called by the builders before save.
	EmailDeliveryErrorKindValidator func(string) error
	// EmailDeliveryClaimTokenValidator is a validator for the "email_delivery_claim_token" field. It is called by the builders before save.
	EmailDeliveryClaimTokenValidator func(string) error
	// DefaultFeishuNotificationStatus holds the default value on creation for the "feishu_notification_status" field.
	DefaultFeishuNotificationStatus string
	// FeishuNotificationStatusValidator is a validator for the "feishu_notification_status" field. It is called by the builders before save.
	FeishuNotificationStatusValidator func(string) error
	// DefaultFeishuNotificationRevision holds the default value on creation for the "feishu_notification_revision" field.
	DefaultFeishuNotificationRevision int
	// DefaultFeishuNotificationAttempts holds the default value on creation for the "feishu_notification_attempts" field.
	DefaultFeishuNotificationAttempts int
	// FeishuNotificationErrorKindValidator is a validator for the "feishu_notification_error_kind" field. It is called by the builders before save.
	FeishuNotificationErrorKindValidator func(string) error
	// FeishuNotificationClaimTokenValidator is a validator for the "feishu_notification_claim_token" field. It is called by the builders before save.
	FeishuNotificationClaimTokenValidator func(string) error
	// DefaultRequestedAt holds the default value on creation for the "requested_at" field.
	DefaultRequestedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PaymentInvoiceRequest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByTitleType orders the results by the title_type field.
func ByTitleType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleType, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByTaxIdentifier orders the results by the tax_identifier field.
func ByTaxIdentifier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxIdentifier, opts...).ToFunc()
}

// ByRecipientEmail orders the results by the recipient_email field.
func ByRecipientEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecipientEmail, opts...).ToFunc()
}

// ByRecipientPhone orders the results by the recipient_phone field.
func ByRecipientPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecipientPhone, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRevision orders the results by the revision field.
func ByRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevision, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByProviderInvoiceID orders the results by the provider_invoice_id field.
func ByProviderInvoiceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderInvoiceID, opts...).ToFunc()
}

// ByInvoiceItemName orders the results by the invoice_item_name field.
func ByInvoiceItemName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceItemName, opts...).ToFunc()
}

// ByInvoiceCode orders the results by the invoice_code field.
func ByInvoiceCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceCode, opts...).ToFunc()
}

// ByInvoiceNumber orders the results by the invoice_number field.
func ByInvoiceNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceNumber, opts...).ToFunc()
}

// ByDocumentFilename orders the results by the document_filename field.
func ByDocumentFilename(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocumentFilename, opts...).ToFunc()
}

// ByDocumentSizeBytes orders the results by the document_size_bytes field.
func ByDocumentSizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocumentSizeBytes, opts...).ToFunc()
}

// ByDocumentSha256 orders the results by the document_sha256 field.
func ByDocumentSha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocumentSha256, opts...).ToFunc()
}

// ByEmailDeliveryStatus orders the results by the email_delivery_status field.
func ByEmailDeliveryStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailDeliveryStatus, opts...).ToFunc()
}

// ByEmailDeliveryAttempts orders the results by the email_delivery_attempts field.
func ByEmailDeliveryAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailDeliveryAttempts, opts...).ToFunc()
}

// ByEmailDeliveryErrorKind orders the results by the email_delivery_error_kind field.
func ByEmailDeliveryErrorKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailDeliveryErrorKind, opts...).ToFunc()
}

// ByEmailDeliveryAttemptedAt orders the results by the email_delivery_attempted_at field.
func ByEmailDeliveryAttemptedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailDeliveryAttemptedAt, opts...).ToFunc()
}

// ByEmailDeliveredAt orders the results by the email_delivered_at field.
func ByEmailDeliveredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailDeliveredAt, opts...).ToFunc()
}

// ByEmailDeliveryClaimToken orders the results by the email_delivery_claim_token field.
func ByEmailDeliveryClaimToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailDeliveryClaimToken, opts...).ToFunc()
}

// ByEmailDeliveryClaimedAt orders the results by the email_delivery_claimed_at field.
func ByEmailDeliveryClaimedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailDeliveryClaimedAt, opts...).ToFunc()
}

// ByEmailDeliveryNextAttemptAt orders the results by the email_delivery_next_attempt_at field.
func ByEmailDeliveryNextAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailDeliveryNextAttemptAt, opts...).ToFunc()
}

// ByFeishuNotificationStatus orders the results by the feishu_notification_status field.
func ByFeishuNotificationStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeishuNotificationStatus, opts...).ToFunc()
}

// ByFeishuNotificationRevision orders the results by the feishu_notification_revision field.
func ByFeishuNotificationRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeishuNotificationRevision, opts...).ToFunc()
}

// ByFeishuNotificationAttempts orders the results by the feishu_notification_attempts field.
func ByFeishuNotificationAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeishuNotificationAttempts, opts...).ToFunc()
}

// ByFeishuNotificationErrorKind orders the results by the feishu_notification_error_kind field.
func ByFeishuNotificationErrorKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeishuNotificationErrorKind, opts...).ToFunc()
}

// ByFeishuNotificationAttemptedAt orders the results by the feishu_notification_attempted_at field.
func ByFeishuNotificationAttemptedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeishuNotificationAttemptedAt, opts...).ToFunc()
}

// ByFeishuNotifiedAt orders the results by the feishu_notified_at field.
func ByFeishuNotifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeishuNotifiedAt, opts...).ToFunc()
}

// ByFeishuNotificationClaimToken orders the results by the feishu_notification_claim_token field.
func ByFeishuNotificationClaimToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeishuNotificationClaimToken, opts...).ToFunc()
}

// ByFeishuNotificationClaimedAt orders the results by the feishu_notification_claimed_at field.
func ByFeishuNotificationClaimedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeishuNotificationClaimedAt, opts...).ToFunc()
}

// ByFeishuNotificationNextAttemptAt orders the results by the feishu_notification_next_attempt_at field.
func ByFeishuNotificationNextAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeishuNotificationNextAttemptAt, opts...).ToFunc()
}

// ByRejectionReason orders the results by the rejection_reason field.
func ByRejectionReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRejectionReason, opts...).ToFunc()
}

// ByProcessedBy orders the results by the processed_by field.
func ByProcessedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessedBy, opts...).ToFunc()
}

// ByRequestedAt orders the results by the requested_at field.
func ByRequestedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedAt, opts...).ToFunc()
}

// ByProcessedAt orders the results by the processed_at field.
func ByProcessedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessedAt, opts...).ToFunc()
}

// ByIssuedAt orders the results by the issued_at field.
func ByIssuedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOrderField orders the results by order field.
func ByOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrderStep(), sql.OrderByField(field, opts...))
	}
}

// ByDocumentField orders the results by document field.
func ByDocumentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDocumentStep(), sql.OrderByField(field, opts...))
	}
}
func newOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, OrderTable, OrderColumn),
	)
}
func newDocumentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DocumentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, DocumentTable, DocumentColumn),
	)
}
