-- Apply only after both production nodes run the reviewed reset-card release.
-- One transaction; refuses a changed catalog or settings. No wallet/rate writes.
\set ON_ERROR_STOP on
BEGIN;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';
LOCK TABLE settings, subscription_plans IN SHARE ROW EXCLUSIVE MODE;
DO $guard$
BEGIN
 IF (SELECT count(*) FROM subscription_plans) <> 0 THEN RAISE EXCEPTION 'Catalog changed: expected no plans'; END IF;
 IF (SELECT COALESCE(jsonb_object_agg(key,value),'{}'::jsonb) FROM settings WHERE key IN ('MIN_RECHARGE_AMOUNT','MAX_RECHARGE_AMOUNT','BALANCE_RECHARGE_MULTIPLIER','SUBSCRIPTION_USD_TO_CNY_RATE','RECHARGE_FEE_RATE','PAYMENT_RECHARGE_OPTIONS','PAYMENT_BANNER','payment_visible_method_alipay_source','payment_visible_method_wxpay_source','payment_visible_method_alipay_enabled','payment_visible_method_wxpay_enabled','ENABLED_PAYMENT_TYPES','payment_enabled')) <> '{"payment_visible_method_wxpay_enabled": "false", "ENABLED_PAYMENT_TYPES": "", "RECHARGE_FEE_RATE": "0.00", "payment_enabled": "false", "MIN_RECHARGE_AMOUNT": "1.00", "BALANCE_RECHARGE_MULTIPLIER": "1.00", "MAX_RECHARGE_AMOUNT": "", "SUBSCRIPTION_USD_TO_CNY_RATE": "", "PAYMENT_RECHARGE_OPTIONS": "[]", "payment_visible_method_wxpay_source": "", "payment_visible_method_alipay_enabled": "false", "payment_visible_method_alipay_source": ""}'::jsonb THEN RAISE EXCEPTION 'Payment settings changed: re-audit before apply'; END IF;
 IF (SELECT count(*) FROM groups WHERE id IN (4,12) AND status='active' AND subscription_type='subscription' AND deleted_at IS NULL) <> 2 THEN RAISE EXCEPTION 'Subscription groups unavailable'; END IF;
 IF to_regclass('public.subscription_reset_card_purchases') IS NULL THEN RAISE EXCEPTION 'Reset purchase migration missing'; END IF;
END $guard$;
INSERT INTO subscription_plans (group_id,name,description,price,original_price,validity_days,validity_unit,features,product_name,for_sale,sort_order,currency,entitlements,created_at,updated_at) VALUES
(4,'Plus 月付','新购与同组续费均可；续费保留剩余有效期',120,NULL,1,'month','["有效订阅可另购重置卡", "重置卡不延长订阅有效期"]','Plus 月付',true,0,'CNY','{}',NOW(),NOW()),(4,'Plus 季付','新购与同组续费均可；续费保留剩余有效期',324.0,360,1,'quarter','["有效订阅可另购重置卡", "重置卡不延长订阅有效期"]','Plus 季付',true,1,'CNY','{}',NOW(),NOW()),(4,'Plus 年付','新购与同组续费均可；续费保留剩余有效期',1152.0,1440,1,'year','["有效订阅可另购重置卡", "重置卡不延长订阅有效期"]','Plus 年付',true,2,'CNY','{}',NOW(),NOW()),(12,'5X Pro 月付','新购与同组续费均可；续费保留剩余有效期',550,NULL,1,'month','["有效订阅可另购重置卡", "重置卡不延长订阅有效期"]','5X Pro 月付',true,10,'CNY','{}',NOW(),NOW()),(12,'5X Pro 季付','新购与同组续费均可；续费保留剩余有效期',1485.0,1650,1,'quarter','["有效订阅可另购重置卡", "重置卡不延长订阅有效期"]','5X Pro 季付',true,11,'CNY','{}',NOW(),NOW()),(12,'5X Pro 年付','新购与同组续费均可；续费保留剩余有效期',5280.0,6600,1,'year','["有效订阅可另购重置卡", "重置卡不延长订阅有效期"]','5X Pro 年付',true,12,'CNY','{}',NOW(),NOW());
INSERT INTO settings (key,value,updated_at) VALUES ('MIN_RECHARGE_AMOUNT','5',NOW()),('MAX_RECHARGE_AMOUNT','0',NOW()),('BALANCE_RECHARGE_MULTIPLIER','1',NOW()),('SUBSCRIPTION_USD_TO_CNY_RATE','0',NOW()),('RECHARGE_FEE_RATE','0',NOW()),('PAYMENT_RECHARGE_OPTIONS','[{"amount":5,"balance_bonus":0,"label":"小额体验","description":"按充值金额到账","sort_order":0,"enabled":true,"recommended":false},{"amount":49,"balance_bonus":0,"label":"轻量充值","description":"按充值金额到账","sort_order":1,"enabled":true,"recommended":false},{"amount":99,"balance_bonus":4,"label":"日常使用","description":"额外赠送 4 额度","sort_order":2,"enabled":true,"recommended":false},{"amount":199,"balance_bonus":19,"label":"进阶充值","description":"额外赠送 19 额度","sort_order":3,"enabled":true,"recommended":false},{"amount":399,"balance_bonus":75,"label":"高频使用","description":"额外赠送 75 额度","sort_order":4,"enabled":true,"recommended":false},{"amount":599,"balance_bonus":145,"label":"畅享充值","description":"额外赠送 145 额度","sort_order":5,"enabled":true,"recommended":true}]',NOW()),('PAYMENT_BANNER','{"enabled":true,"title":"订阅与余额充值","description":"Plus / 5X Pro 月付、季付、年付可选；余额充值最高赠送 145 额度。","link_url":"/subscriptions","button_text":"查看我的订阅"}',NOW()),('payment_visible_method_alipay_source','unified_alipay',NOW()),('payment_visible_method_wxpay_source','unified_wxpay',NOW()),('payment_visible_method_alipay_enabled','true',NOW()),('payment_visible_method_wxpay_enabled','true',NOW()),('ENABLED_PAYMENT_TYPES','alipay,wxpay',NOW()),('payment_enabled','true',NOW())
ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value,updated_at=EXCLUDED.updated_at;
SELECT id,group_id,name,price,original_price,currency,validity_days,validity_unit,for_sale FROM subscription_plans ORDER BY sort_order,id;
COMMIT;
